### ISSUE TITLE
"TypeError: dispatcher.useInsertionEffect is not a function" after upgrading from ^5.3.3 to ^5.4.0

### ISSUE THREAD

**Issue by devj3ns** [mantinedev/mantine#2880] opened 2022-11-04 21:16 UTC
### What package has an issue

@mantine/core

### Describe the bug

I am using mantine version `^5.3.3` with next.js `13.0.1`.

When I upgrade to a newer mantine version, e.g. `^5.4.0` or  `^5.7.0` I get the following error when opening my website:

```
error - TypeError: dispatcher.useInsertionEffect is not a function
    at useInsertionEffect (C:\pathToMyProject\node_modules\react\cjs\react.development.js:1638:21)
    at useEvent (C:\pathToMyProject\node_modules\@floating-ui\react-dom-interactions\dist\floating-ui.react-dom-interactions.umd.js:186:7)
    at Object.useFloating (C:\pathToMyProject\node_modules\@floating-ui\react-dom-interactions\dist\floating-ui.react-dom-interactions.umd.js:223:26)
    at Object.usePopover (C:\pathToMyProject\node_modules\@mantine\core\cjs\Popover\use-popover.js:45:41)
    at Popover (C:\pathToMyProject\node_modules\@mantine\core\cjs\Popover\Popover.js:134:30)   
    at renderWithHooks (C:\pathToMyProject\node_modules\react-ssr-prepass\dist\react-ssr-prepass.js:454:15)
    at render$2 (C:\pathToMyProject\node_modules\react-ssr-prepass\dist\react-ssr-prepass.js:465:6)
    at C:\pathToMyProject\node_modules\react-ssr-prepass\dist\react-ssr-prepass.js:612:12      
    at render (C:\pathToMyProject\node_modules\react-ssr-prepass\dist\react-ssr-prepass.js:613:4)
    at visitElement (C:\pathToMyProject\node_modules\react-ssr-prepass\dist\react-ssr-prepass.js:725:15) {
  page: '/webinars/[id]'
}
```

Thanks for this awesome library and taking the time to read this issue :)

### What version of @mantine/hooks page do you have in package.json?

^5.4.0

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

**Comment by quick0831** [comment] 2022-11-05 06:48
I found a same error
Just running `next dev` cause me this

`@mantine/core` version: `^5.6.3`

```
error - TypeError: dispatcher.useInsertionEffect is not a function
    at useInsertionEffect (C:\pathToMyProject\node_modules\react\cjs\react.development.js:1638:21)
    at useEvent (C:\pathToMyProject\node_modules\@floating-ui\react-dom-interactions\dist\floating-ui.react-dom-interactions.umd.js:186:7)
    at Object.useFloating (C:\pathToMyProject\node_modules\@floating-ui\react-dom-interactions\dist\floating-ui.react-dom-interactions.umd.js:223:26)
    at Object.useTooltip (C:\pathToMyProject\node_modules\@mantine\core\cjs\Tooltip\use-tooltip.js:34:28)
    at C:\pathToMyProject\node_modules\@mantine\core\cjs\Tooltip\Tooltip.js:143:30
    at renderWithHooks (C:\pathToMyProject\node_modules\react-ssr-prepass\dist\react-ssr-prepass.js:454:15)
    at render$2 (C:\pathToMyProject\node_modules\react-ssr-prepass\dist\react-ssr-prepass.js:465:6)
    at C:\pathToMyProject\node_modules\react-ssr-prepass\dist\react-ssr-prepass.js:612:12
    at render (C:\pathToMyProject\node_modules\react-ssr-prepass\dist\react-ssr-prepass.js:613:4)
    at visitElement (C:\pathToMyProject\node_modules\react-ssr-prepass\dist\react-ssr-prepass.js:725:15) {
  page: '/'
}
```

**Comment by quick0831** [comment] 2022-11-05 06:55
downgrading to `5.3.3` solved my problem

**Comment by rtivital** [comment] 2022-11-05 07:20
Update react and react dom versions to 18, reinstall dependencies – https://stackoverflow.com/questions/71682733/react-select-error-on-upgrade-typeerror-dispatcher-useinsertioneffect-is-not-a

Duplicate of #2609

**Closed by rtivital** 2022-11-05 07:20 UTC
Labels: review required

**Comment by devj3ns** [comment] 2022-11-05 14:15
My react and react-dom dependencies are >18:

```
"react": "^18.2.0",
"react-dom": "^18.2.0",
```

I guess that's not the problem.

**Comment by rtivital** [comment] 2022-11-05 14:27
Try reinstalling dependencies and cleaning cache, you can also use mantine-next-template, it does not have such issue

**Comment by devj3ns** [comment] 2022-11-29 11:36
@quick0831 Since you are getting the exact error as me: Are you also using tRPC with SSR enabled?

**Comment by quick0831** [comment] 2022-11-29 11:40
Add "ssr":false make it work

**Comment by devj3ns** [comment] 2022-11-29 11:42
Yes, I know. But ideally, it should work with SSR too. So, there is an issue somewhere.

**Comment by quick0831** [comment] 2022-11-29 11:44
Actually I forgot it. I remember turning off ssr in trpc and it stop complaining.

**Comment by angelvega93** [comment] 2023-03-15 05:15
Did you fix it?, im having the same problem with react-ssr-prepass

**Comment by devj3ns** [comment] 2023-03-15 20:29
@angelvega93 

After upgrading to the newest mantine version (`6.02`) and next version (`13.2.5`), I am getting the following error:

```
Uncaught TypeError: useInsertionEffect only works in Client Components. Add the "use client" directive at the top of the file to use it. Read more: https://nextjs.org/docs/messages/react-client-hook-in-server-component
    at useInsertionEffect (file://C:\pathToMyProject\node_modules\react\cjs\react.development.js:1638:21)
    at useEvent (file://C:\pathToMyProject\node_modules\@floating-ui\react\dist\floating-ui.react.umd.js:1335:5)
    at Object.useFloating (file://C:\pathToMyProject\node_modules\@floating-ui\react\dist\floating-ui.react.umd.js:3806:26)
    at Object.useTooltip (file://C:\pathToMyProject\node_modules\@mantine\core\cjs\Tooltip\use-tooltip.js:34:13)
    at <unknown> (file://C:\pathToMyProject\node_modules\@mantine\core\cjs\Tooltip\Tooltip.js:148:30)
    at renderWithHooks (file://C:\pathToMyProject\node_modules\react-ssr-prepass\dist\react-ssr-prepass.js:454:15)
    at render$2 (file://C:\pathToMyProject\node_modules\react-ssr-prepass\dist\react-ssr-prepass.js:465:6)
    at <unknown> (file://C:\pathToMyProject\node_modules\react-ssr-prepass\dist\react-ssr-prepass.js:612:12)
    at render (file://C:\pathToMyProject\node_modules\react-ssr-prepass\dist\react-ssr-prepass.js:613:4)
    at visitElement (file://C:\pathToMyProject\node_modules\react-ssr-prepass\dist\react-ssr-prepass.js:725:15)
    at visitLoop (file://C:\pathToMyProject\node_modules\react-ssr-prepass\dist\react-ssr-prepass.js:742:17)
    at update (file://C:\pathToMyProject\node_modules\react-ssr-prepass\dist\react-ssr-prepass.js:801:9)
    at <unknown> (file://C:\pathToMyProject\node_modules\react-ssr-prepass\dist\react-ssr-prepass.js:878:5)
    at async Function.WithTRPC.getInitialProps (webpack-internal:///./node_modules/@trpc/next/dist/index.mjs:122:21)
```

Note: I am not using the next.js app directory.

When I disable SSR in tRPC, the error disappears.

So, there is still an issue with newer mantine versions and SSR.

**Comment by rtivital** [comment] 2023-03-16 05:00
You can use one of the templates as reference. Templates do not have ssr issues.

**Comment by esistgut** [comment] 2023-03-22 19:05
I'm having the same problem, just upgraded everything with `npx npm-check-updates -u` and the problem persists. Did anyone here find a way to fix this?

**Comment by isoaxe** [comment] 2023-03-31 07:42
I'm having the same issue. Unfortunately I can't use one of the suggested templates as @rtivital has suggested as I'm already using a Next / tRPC [template](https://github.com/trpc/examples-next-minimal-starter). Tried clearing the cache and reinstalling deps to no avail.

Had to go with turning off SSR in the tRPC config for now. Hopefully there will be a fix that doesn't require this down the line.

**Comment by Sameer3079** [comment] 2023-04-29 13:44
> I'm having the same `TypeError: useInsertionEffect only works in Client Components` issue. Unfortunately I can't use one of the suggested templates as @rtivital has suggested as I'm already using a Next / tRPC [template](https://github.com/trpc/examples-next-minimal-starter). Tried clearing the cache and reinstalling deps to no avail.
> 
> Had to go with turning off SSR in the tRPC config for now. Hopefully there will be a fix that doesn't require this down the line.
> 
> _Note:_ After some messing around, I found that I don't get the error with some of the components even with SSR enabled. It appears the Mantine's `<Select/>` component was the offending one for me. Maybe others can corroborate?

It was the same for me. Commenting out the `<Select />` component worked for me. I wonder why that is.

**Comment by henningsieh** [comment] 2023-05-07 07:03
I use Mantine, but without any <Select/> until now and the error is still there with "@mantine/core": "^6.0.10".

There still must be another mantine component, which breaks tRPC SSR. :(

**Comment by peter-wd-1** [comment] 2023-06-22 12:33
Is there any workaround to use tRPC `SSR:true` with Mantine?

**Comment by FernandoNarvaez1904** [comment] 2023-07-03 02:43
@peter-wd-1 @henningsieh 
I also found that the Select component was giving me the `useInsretionEffectError`. The workaround I found in next is dynamically import the component with SSR: off in the import, like so:

```typescript
// Load completely on the client to avoid ssr error
const Select = dynamic(() => import("@mantine/core").then((el) => el.Select), {
  loading: () => <p>Loading...</p>,
  ssr: false,
});
``` 

It works well for what I am doing, I hope this helps someone else.

**Comment by Telofy** [comment] 2023-10-16 08:17
Tooltips are also broken. Here's a solution specific to tooltips that avoids that pieces of the text (the ones with the tooltips) are missing or replaced with “Loading…” during the dynamic load.

```
// Load completely on the client to avoid SSR error
// https://github.com/mantinedev/mantine/issues/2880#issuecomment-1617136855
import dynamic from 'next/dynamic'

import { TooltipBaseProps } from '@mantine/core/lib/components/Tooltip/Tooltip.types'

export const Tooltip = ({ children, ...rest }: TooltipBaseProps) => {
  const MantineTooltip = dynamic(
    () => import('@mantine/core').then((el) => el.Tooltip),
    {
      loading: () => <>{children}</>,
      ssr: false,
    },
  )

  return <MantineTooltip {...rest}>{children}</MantineTooltip>
}
```

**Comment by luixo** [comment] 2023-12-07 04:14
Probably this is during the `react-ssr-prepass` [issue](https://github.com/FormidableLabs/react-ssr-prepass/issues/84), the package is not actively maintained but used in SSR render of tRPC.

I stumbled upon the same error in another library though.

**Comment by apeck14** [comment] 2024-03-06 01:01
@Telofy Do you know if your workaround is still required on latest? (7.6.1)
