### ISSUE TITLE
Select does not close Dropdown on clicking outside

### ISSUE THREAD

**Issue by kvndrsslr** [mantinedev/mantine#7000] opened 2024-10-21 07:54 UTC
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.13.3

### What package has an issue?

@mantine/core

### What framework do you use?

Vite

### In which browsers you can reproduce the issue?

Not applicable – issue is not related to the browser

### Describe the bug

Upon clicking outside of the Select Component or its Dropdown area, the Dropdown area stays opened. This can be observed on the official docs site as well: https://mantine.dev/core/select/

In `7.13.2` clicking outside closed the Dropdown and I found no information in the releases page that this change was intentional.

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by DreierF** [comment] 2024-10-21 10:22
Might this be caused by https://github.com/mantinedev/mantine/commit/bb19ad7877ab9532b26366d9a7601d1615cb6fb8#r148160464 ?

A similar issue is that controlled popups no longer close on pressing ESC.

Reproduction: https://codesandbox.io/p/sandbox/dh3ddv

**Comment by rcapulsuhay** [comment] 2024-10-22 01:13
this happen to me after updating to 7.13.3, i just have to roll back to 7.13.2 to fix the issue for now.

**Comment by rtivital** [comment] 2024-10-23 17:00
Fixed in [7.13.4](https://github.com/mantinedev/mantine/releases/tag/7.13.4)

**Closed by rtivital** 2024-10-23 17:00 UTC
Labels: Fixed patch
