### ISSUE TITLE
Select overflow in card component

### ISSUE THREAD

**Issue by indietyp** [mantinedev/mantine#264] opened 2021-09-22 08:18 UTC
* **Package:** @mantine/core
* **Version:** 2.5.x
* **Browser:** Firefox 93.0b8 _Developer Edition_
* **OS:** macOS 11.6
* **Code Sandbox:** https://codesandbox.io/s/magical-bush-cytqf

The problem is that the select dropdown of items is getting cut off, making it impossible to use in a card (or modal) component. A way to solve this would be by wrapping the dropdown using a [Popper](https://mantine.dev/core/popper/) component. That way, the dropdown would be rendered outside of the tree, eliminating the cut-off.

I would be willing to create a fix (and subsequent pull request) if needed. The difficulty of implementation should be easy tho.

**Comment by rtivital** [comment] 2021-09-22 08:22
Hi @indietyp wrapping dropdown in Popper is not as easy as you think, we already have an issue for that #202 you can read everything about logic that comes with this change. 
Please just set overflow to visible to fix this issue for now – https://codesandbox.io/s/hungry-edison-z4w9q?file=/src/App.js

Duplicate of #202

**Closed by rtivital** 2021-09-22 08:22 UTC

**Comment by indietyp** [comment] 2021-09-22 08:26
Thanks, I completely missed the issue mentioned. Sorry and thanks for the swift reply!
