### ISSUE TITLE
Controlled NumberInput internal value not updating after value prop updates in onChange

### ISSUE THREAD

**Issue by timvandam** [mantinedev/mantine#689] opened 2022-01-17 13:40 UTC
### What package has an issue

@mantine/core

### Describe the bug

When updating the value prop of a NumberInput inside of the onChange, the internal value (thus the displayed value) does not change

### In which browser did the problem occur

Google Chrome

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/cool-einstein-qhr6z?file=/src/App.tsx:192-250

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Possible fix

https://github.com/mantinedev/mantine/blob/a7ea3ba2879bb2a82d048247d405785be234cd36/src/mantine-core/src/components/NumberInput/NumberInput.tsx#L172-L181

The displayed value (tempValue) updated to the prop value only if the NumberInput is not focused, and the noChange function is called when the NumberInput is still focused. Thus also calling this useEffect when the focus changes would ensure that tempValue is up to date

**Comment by manansharma18** [comment] 2022-03-22 02:29
Please assign this to me and I can have a look at this. Would be happy to help

**Comment by manansharma18** [comment] 2022-03-23 01:18
Hey,
How can I debug this component?

**Comment by rtivital** [comment] 2022-03-23 09:59
https://mantine.dev/pages/contributing/#get-started-with-mantine-locally

**Comment by auronsan** [comment] 2022-05-19 18:13
@rtivital Not A bug. work normally when not focus.
Tested the issue is not UI friendly and lead ugliness if try fixing it. caused stuck on number forever. 
Like 0 to 0123 caused 0 persistent

https://codesandbox.io/s/focused-rosalind-s1t18z?file=/src/App.tsx

**Comment by rtivital** [comment] 2022-05-19 19:59
Okay, thanks @auronsan

**Closed by rtivital** 2022-05-19 19:59 UTC
Labels: bug
