### ISSUE TITLE
Menu.Dropdown position is incorrectly calculated on mount

### ISSUE THREAD

**Issue by gigobyte** [mantinedev/mantine#2397] opened 2022-09-08 20:42 UTC
### What package has an issue

@mantine/core

### Describe the bug

In my application I have a `Menu` component rendered at the right end of the page and I found that it takes a couple of rerenders for the `Popover` inside the menu to figure the correct `left` style of the dropdown.

Example of the incorrect behaviour:

![GIF](https://user-images.githubusercontent.com/8791446/189220819-03d54e74-61c9-4316-99a7-61a06e2e9cc2.gif)

Rerenders can be triggered by repeatedly clicking the toggle button or by resizing the window.

### What version of @mantine/hooks page do you have in package.json?

5.2.5

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/musing-morning-65xqhz?file=%2Fsrc%2FApp.tsx

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Possible fix

From my research here's what I found out:

- The issue is present only if the `Menu` parent element has a right padding/margin.
- It doesn't matter how the `Menu` is pushed to the end, both `margin-left: auto` and `justify-content: flex-end` result in the same problem
- This is not related to transitions as setting `transitionDuration` to 0 changes nothing

**Comment by rtivital** [comment] 2022-09-09 05:01
Hi @gigobyte, I think that this issue is caused by Menu size being recalculated on dropdown mount, to fix that issue, add width to Menu – https://codesandbox.io/s/floral-sky-z03pt7?file=/src/App.tsx

**Comment by gigobyte** [comment] 2022-09-09 08:12
Setting the width would obviously fix the issue, but if I remove the right padding the width is automatically calculated even on first mount. Is there any way to go around that?

**Comment by rtivital** [comment] 2022-09-09 08:22
I do not know, it depends on how floating ui calculates position of elements that are being mounted to the dom with animation.

**Comment by rtivital** [comment] 2022-09-14 13:28
Closing this, as it can be fixed by setting width

**Closed by rtivital** 2022-09-14 13:28 UTC
