### ISSUE TITLE
General scroll problem with ScrollArea

### ISSUE THREAD

**Issue by waldimiro** [mantinedev/mantine#7295] opened 2024-12-21 13:10 UTC
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.15.1

### What package has an issue?

@mantine/core

### What framework do you use?

create-react-app (CRA)

### In which browsers you can reproduce the issue?

All

### Describe the bug

Everywhere (even on the official Mantine page https://mantine.dev/core/scroll-area/) the first scroll of the component does not work or rather, is not displayed by the component. at a second scroll the component actually reflects the position of the thumb

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment] 2024-12-21 14:58
Duplicate of #7257

**Closed by rtivital** 2024-12-21 14:58 UTC
