### ISSUE TITLE
mantine 7.0 Dropzone error

### ISSUE THREAD

**Issue by showbizace** [mantinedev/mantine#4921] opened 2023-09-29 08:21 UTC
### What package has an issue

@mantine/core

### Describe the bug

after i install mantine 7.1.0 this error occurred 

SyntaxError: Named export 'useDropzone' not found. The requested module 'react-dropzone' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'react-dropzone';
const { useDropzone } = pkg;

i'm using { Dropzone } from @mantine/dropzone 

### What version of @mantine/* packages do you have in package.json? (Note that all @mantine/* packages must have the same version in order to work correctly)

7.1.0

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by rtivital** [comment] 2023-09-29 08:28
Duplicate of https://github.com/mantinedev/mantine/issues/4920

**Closed by rtivital** 2023-09-29 08:28 UTC
