### ISSUE TITLE
Mantine Drawer not working in production environment

### ISSUE THREAD

**Issue by lahin31** [mantinedev/mantine#4651] opened 2023-08-14 08:50 UTC
### What package has an issue

@mantine/core

### Describe the bug

In development mode Drawer working as expected but when I use DigitalOcean's Droplet, this is not working. Here is the picture,
<img width="734" alt="Screenshot 2023-08-14 at 2 44 30 PM" src="https://github.com/mantinedev/mantine/assets/12637865/95fcf2a5-8e0f-46c3-ae2e-dba51f3539c3">
In every places where I used it(Drawer), I am getting this error. 
@mantine/core version is ^5.10.5

### What version of @mantine/hooks page do you have in package.json?

^5.10.0

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by abdullahqasemi** [comment] 2023-08-14 09:11
I am facing a similar issue using mantine version "6.0.18".

**Comment by rtivital** [comment] 2023-08-14 09:34
Duplicate of https://github.com/mantinedev/mantine/issues/4548

**Closed by rtivital** 2023-08-14 09:34 UTC

**Comment by lahin31** [comment] 2023-08-14 10:24
I don't see any solution for version 5. Can you help me on this? @rtivital 

> Duplicate of #4548
