### ISSUE TITLE
Notifications with strict mode (findDOMNode warning)

### ISSUE THREAD

**Issue by zifeo** [mantinedev/mantine#378] opened 2021-11-03 17:47 UTC
Relates to https://github.com/mantinedev/mantine/issues/93 but in @mantine/notifications@3.1.4 (latest Safari).

```
notifications.showNotification({
  message: `Success!`,
});
```

```
Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of Transition which is inside StrictMode. Instead, add a ref directly to the element you want to reference. Learn more about using refs safely here: https://reactjs.org/link/strict-mode-find-node
```

**Comment by rtivital** [comment] 2021-11-03 17:50
We need to migrate @mantine/notifications to new ref api to remove this warning, feel free to submit a PR

**Comment by bogordesaincom** [comment] 2021-11-08 11:52
same problem

**Comment by bogordesaincom** [comment] 2021-11-26 03:35
any solution for this?, i'm search but still not found

**Comment by Cheesetouched** [comment] 2022-02-04 09:51
Same issue. Is this patched in the latest release?

**Comment by rtivital** [comment] 2022-02-04 12:07
No, until issue is closed it is not patched

**Comment by rtivital** [comment] 2022-02-18 19:40
The issue is fixed, the fix will be released with 4.0 release

**Comment by bogordesaincom** [comment] 2022-02-22 06:43
amazing @rtivital thanks

**Comment by maticrivo** [comment] 2022-02-24 19:15
@rtivital is there an ETA on 4.0 release?

**Comment by rtivital** [comment] 2022-02-24 19:22
End of march - mid april

**Closed** 2022-03-10 15:48 UTC
Labels: bug

**Comment by devkwaku** [comment] 2022-10-04 10:14
Issue present in `@mantine/core": "^5.3.2"`

Example code
```import { Input } from '@mantine/core';
import { useId } from '@mantine/hooks';
import InputMask from 'react-input-mask';

function Demo() {
  const id = useId();
  return (
    <Input.Wrapper id={id} label="Your phone" required>
      <Input component={InputMask} mask="+7 (999) 999-99-99" id={id} placeholder="Your phone" />
    </Input.Wrapper>
  );
}

**Comment by rtivital** [comment] 2022-10-04 10:43
It is issue of react-input-mask package, not Mantine
