### ISSUE TITLE
Firefox shows rem warnings after recent 6.0 upgrade

### ISSUE THREAD

**Issue by imoby** [mantinedev/mantine#3885] opened 2023-03-24 02:44 UTC
### What package has an issue

@mantine/core

### Describe the bug

After migrating to mantine 6.0, I started to notice these warnings on rem on firefox.

<img width="863" alt="image" src="https://user-images.githubusercontent.com/6380855/227410961-0ecf430e-21e5-42f8-b793-50e85fdfad21.png">

### What version of @mantine/hooks page do you have in package.json?

6.04

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

**Comment by rtivital** [comment] 2023-03-24 05:09
Duplicate of #3699

**Closed by rtivital** 2023-03-24 05:09 UTC
Labels: review required
