### ISSUE TITLE
After upgrading to v5.5.5, the Menu in AppHeader causes React to redraw frequently

### ISSUE THREAD

**Issue by GZTimeWalker** [mantinedev/mantine#2693] opened 2022-10-12 16:45 UTC
### What package has an issue

@mantine/core

### Describe the bug

After upgrade to v5.5.5, all the pages had 100% CPU usage, and the problem disappeared after the downgrade to v5.5.4

<img width="1343" alt="image" src="https://user-images.githubusercontent.com/28180262/195400763-3c1594d2-89f4-4f34-bb87-6d78c6ca5c75.png">

It seems to be caused by `MenuItem` and `Box`, in the last version these functions were no more than 10ms

<img width="780" alt="image" src="https://user-images.githubusercontent.com/28180262/195407323-40cb45df-9065-4398-9e18-38be29819733.png">

<img width="1208" alt="image" src="https://user-images.githubusercontent.com/28180262/195409001-e10833a8-e167-4209-b91c-ec3959c60b4e.png">

<img width="1185" alt="截屏2022-10-13 01 28 39" src="https://user-images.githubusercontent.com/28180262/195409194-51226a3e-04fc-4943-bdb2-702dba30789e.png">

### What version of @mantine/hooks page do you have in package.json?

^5.5.5

### If possible, please include a link to a codesandbox with the reproduced problem

- [https://codesandbox.io/s/quirky-yalow-373rs0?file=/src/Header.tsx](https://codesandbox.io/s/quirky-yalow-373rs0?file=/src/Header.tsx)

**Comment by rtivital** [comment] 2022-10-12 17:47
There were no changes to these components in 5.5.5 release. I also cannot reproduce any performance issues in the sandbox – https://codesandbox.io/s/dreamy-dijkstra-mche2z?file=/src/App.tsx
Most likely the issue is on your side.

**Comment by GZTimeWalker** [comment] 2022-10-12 17:52
Ok, I'm gonna find out what happened in the sandbox, catch you later.

**Comment by GZTimeWalker** [comment] 2022-10-12 18:01
> There were no changes to these components in 5.5.5 release. I also cannot reproduce any performance issues in the sandbox – https://codesandbox.io/s/dreamy-dijkstra-mche2z?file=/src/App.tsx Most likely the issue is on your side.

Here you are.

- [https://codesandbox.io/s/quirky-yalow-373rs0?file=/src/Header.tsx](https://codesandbox.io/s/quirky-yalow-373rs0?file=/src/Header.tsx)

**Comment by GZTimeWalker** [comment] 2022-10-12 18:09
It may be related to #2646 and #2690

**Comment by rtivital** [comment] 2022-10-12 18:11
https://codesandbox.io/s/vigilant-roman-fi3xhx?file=/src/Header.tsx

**Comment by GZTimeWalker** [comment] 2022-10-12 18:14
> https://codesandbox.io/s/vigilant-roman-fi3xhx?file=/src/Header.tsx

thx, it works now.

**Comment by fdb75017** [comment] 2022-10-13 11:51
Hello @rtivital , I'm having an issue that I think is linked here, see:
https://codesandbox.io/s/happy-dawn-84oqzm?file=/src/App.js

Not exactly trying to have a "controlled" menu, but rather just register when it is opened. It seems as soon as I attach the `onOpen` event, the `Menu` starts to behave strangely. When the button is clicked the first time, the `onOpen` callback gets fired but the `Menu` does not open. If I click a second time, then the menu opens. 

What do you think ? Maybe I'm misunderstanding the use of `onOpen` ?
Many thanks !

**Comment by rtivital** [comment] 2022-10-13 14:29
Okay, I'll check that, thanks for reporting

**Comment by wes337** [comment] 2022-10-13 19:24
> Hello @rtivital , I'm having an issue that I think is linked here, see: https://codesandbox.io/s/happy-dawn-84oqzm?file=/src/App.js
> 
> Not exactly trying to have a "controlled" menu, but rather just register when it is opened. It seems as soon as I attach the `onOpen` event, the `Menu` starts to behave strangely. When the button is clicked the first time, the `onOpen` callback gets fired but the `Menu` does not open. If I click a second time, then the menu opens. But it doesn't close if you click outside.
> 
> (happens since 5.5.5)
> 
> What do you think ? Maybe I'm misunderstanding the use of `onOpen` ? Many thanks !

Is this the issue in question here? Is this the original issue from @GZTimeWalker about redrawing and using 100% CPU resolved?

**Comment by atumas-bananamilk** [comment] 2022-10-15 13:06
I face this issue when I add `onChange` to my Menu. Seems like the state becomes delayed by 1 step.

**Comment by rtivital** [comment] 2022-10-18 17:19
The changes were reverted, should be fixed on 5.5.6

**Closed by rtivital** 2022-10-18 17:19 UTC
Labels: completed
