### ISSUE TITLE
Controlled NumberInput with precision buggy formatting

### ISSUE THREAD

**Issue by dbrxnds** [mantinedev/mantine#3663] opened 2023-03-03 14:00 UTC
### What package has an issue

@mantine/core

### Describe the bug

A controlled NumberInput tries to format the input on every change causing it to sometimes ignore certain inputs or remove characters you put in.

You can especially notice this when using the `precision` prop, where it tries to format to the set precision on every change, making it hard to type.

### What version of @mantine/hooks page do you have in package.json?

6.0

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/intelligent-sound-dxxsf9?file=/src/App.tsx

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

**Comment by cyantree** [comment] 2023-03-09 16:40
Maybe I find some time for it over the weekend. But I can't promise.

**Comment by cyantree** [comment] 2023-03-09 19:54
Feel free to take over @frec-hansen if you have a hunch. 👍

**Comment by cyantree** [comment] 2023-03-10 23:21
@frec-hansen 
I think the line you highlighted just formats a new incoming value for the text field. That's ok.

IMHO the issue is related to this:
https://github.com/mantinedev/mantine/blob/15f1be8a8467e38c80ba213a51546630a23a888d/src/mantine-core/src/NumberInput/NumberInput.tsx#L192

`handleValueChange()` gets triggered on various occasions and also every input change and therefore results in the observered behaviour.

Here's my proposal:
Only call `onChange()` when bluring the input, clicking the increment/decrement buttons or using the increment/decrement ref methods.

Before sending out the new value parse it, validate it, clamp it (if configured). Invalid values then get discarded and returned as `''`.
This is mostly in line with this response: https://github.com/mantinedev/mantine/issues/3657#issuecomment-1453266553
The difference is that I wouldn't remove the formatting when focussing as this might for example lead to switching decimal separators which might irritate.

Does this sound like a good approach?

**Comment by frec-hansen** [comment] 2023-03-10 23:30
@cyantree  I think you have more context that I do. I just compared the latest version with a working version and noticed that might be the problem since in v5: 
https://github.com/mantinedev/mantine/blob/15f1be8a8467e38c80ba213a51546630a23a888d/src/mantine-core/src/NumberInput/NumberInput.tsx#L250
Won't run unless we lose focus. But again. You probably know better.

**Comment by cyantree** [comment] 2023-03-10 23:48
The loop is the following:
1. The initial `value` is `0.5`.
2. The hook you linked will `setTempValue()` to `0,50` because of the configured precision.
3. One focuses the input field and appends a `1` to `0,50`, so the field reads `0,501`
4. Because of the change `handleChange()` gets called which then calls `handleValueChange()`
5. `handleValueChange()` then calls `onChange()` because the entered value is valid and differs from the last one
6. The `setValue()` handler within the app code gets called and sets `value` to `0.501`.
7. This triggers a rerendering which passes `0.501` as value to `NumberInput`.
8. This then triggers the hook you linked which will then `setTempValue()` back to `0,50` because of the configured precision.

So by stopping at 5. we avoid passing an "in progress" value to the outside.

I think it worked in v5 because of this condition:
https://github.com/mantinedev/mantine/blob/5.10.5/src/mantine-core/src/NumberInput/NumberInput.tsx#L250
This may have resulted in preventing step 8 as long as the input field was focussed. (I haven't actually checked it out)
But that may have resulted in `value` getting out of sync with the internal state. Or why did you remove this @rtivital?

**Comment by bulicmatko** [comment] 2023-03-10 23:58
Maybe formatting should be applied only after the blur (in a way that does not affect the input value).

When the user focuses on the input, formatting should be removed so the user is free to type in a number in a browser native way. After input is done and the user moves away from NumberInput, formatting can be applied without messing with the input value.

The problem with formatting onChange causes the cursor to jump through the string.

**Comment by cyantree** [comment] 2023-03-12 00:23
I've prepared a PR in #3756. It would be great if some of you could give me some feedback as it contains some bigger changes.

**Comment by cyantree** [comment] 2023-03-12 14:03
Feel free to checkout the patched version in this sandbox:
https://codesandbox.io/s/mantine-numberinput-issues-2x16u7

You may also try out the patched version in your project to verify the fix.

**Comment by aheissenberger** [comment] 2023-03-14 08:58
**QuickFix:** adding `removeTrailingZeros={true}` together with `precision={2}` fixed the input problems and shows the digits.

I still think the default should not be `precision="0"` and there is no option to disable precision to show all decimal digits

**Comment by cyantree** [comment] 2023-03-14 16:50
I agree. The default rounding behaviour is a bit unobvious.
Changing it would be a breaking change IMHO.
One could argue that it may not be too late for the breaking change to add it now as the component is currently quite broken anyway. But that's not for me to decide.

Allowing `precision={false}` or `precision={true}` might be an option to disable rounding altogether. However this could also lead to displaying inaccuracies (e. g. for `value={.1 + .2}` which results in `0.30000000000000004`)
Which is better?
- `precision={false}` as in "Disable precission handling" (however that might be confused with "no precision" as in "remove precision and round to the next integer")
- `precision={true}` as in "Enable full precission"

I'm leaning towards `precision={true}` because it also can be written as shorthand.

**Comment by rtivital** [comment] 2023-03-21 07:05
Fixed in 6.0.3

**Closed** 2023-03-21 07:04 UTC
Labels: help wanted
