### ISSUE TITLE
[RangeCalendar] days are not accessible by keyboard when the month has changed. 

### ISSUE THREAD

**Issue by ethanrdavis** [mantinedev/mantine#3412] opened 2023-01-24 08:53 UTC
### What package has an issue

@mantine/dates

### Describe the bug

When accessing the RangeCalendar component by keyboard, it is possible to tab into the first date of the month, and then change the day with the arrow keys. 

But if you change the month using the keyboard, you are then unable to tab into any days in the new month. 

Upon inspection it looks as though no day from the new month is given a tabIndex={0}.

https://user-images.githubusercontent.com/83648061/214248897-3312cc4a-eb59-44c8-bcd6-d3777c1e89af.mov

### What version of @mantine/hooks page do you have in package.json?

5.1.6

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

### Possible fix

It looks as though, whenever a month changes, the first day of the new month should be given a tabIndex={0}

**Comment by rtivital** [comment] 2023-01-24 13:04
The issue is fixed in 6.0 – https://v6.mantine.dev/dates/calendar/

**Comment by rtivital** [comment] 2023-03-03 06:50
Fixed in 6.0

**Closed by rtivital** 2023-03-03 06:50 UTC
Labels: completed-in-6.0
