### ISSUE TITLE
a11y: radio / checkbox group items are not grouped programmatically

### ISSUE THREAD

**Issue by Kinbaum** [mantinedev/mantine#3170] opened 2022-12-12 14:13 UTC
### What package has an issue

@mantine/core

### Describe the bug

Radio / checkbox group items are not grouped programmatically. Assistive technology users will not be aware of the association between the group label and each radio button in that group.

### What version of @mantine/hooks page do you have in package.json?

5.9.4

### If possible, please include a link to a codesandbox with the reproduced problem

https://mantine.dev/core/radio/#radiogroup-component

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

### Possible fix

Wrap the group label and radio / checkbox options in a `<fieldset>` element. Wrap the group label in a `<legend>` element and ensure that the `<legend>` element is the first child of the `<fieldset>` element.

When using a `description`, the `<fieldset>` element should contain an `aria-describedby` attribute.

If the field has an error and a description, they would both be referenced in the `aria-describedby` attribute, with the error first and description second. So if the error had an `id="error-1"` and the description was `id="desc-1"`, the attribute on the `<fieldset>` would be `aria-describedby="error-1 desc-1"`

Then when the error is cleared it would go back to just `aria-describedby="desc-1"`

**Comment by rtivital** [comment] 2023-09-25 13:12
The issue is resolved in [7.0.1](https://github.com/mantinedev/mantine/releases/tag/7.0.1)

**Closed by rtivital** 2023-09-25 13:12 UTC
Labels: Completed patch
