### ISSUE TITLE
SegmentedControl bug after deploy

### ISSUE THREAD

**Issue by alexbakers** [mantinedev/mantine#2454] opened 2022-09-15 11:09 UTC
### What package has an issue

@mantine/core

### Describe the bug

Hello,

Dev localhost `yarn dev`

<img width="194" alt="image" src="https://user-images.githubusercontent.com/98721968/190387979-84047725-a844-46bd-9b19-63e49fa9594a.png">

<img width="572" alt="image" src="https://user-images.githubusercontent.com/98721968/190388502-f49db58d-1f85-4a85-924a-2991b62ddea1.png">

After deployment `yarn build`

<img width="230" alt="image" src="https://user-images.githubusercontent.com/98721968/190388034-b7173da8-bf52-4dde-b9cc-3e44d999307c.png">

span element disappears after deployment.

<img width="467" alt="image" src="https://user-images.githubusercontent.com/98721968/190388441-24103549-a377-4656-85ef-517c94b4b5e8.png">

while the switch works, but there is no color

Using http://vitejs.dev

### What version of @mantine/hooks page do you have in package.json?

^5.3.0

### Do you know how to fix the issue

No

**Comment by rtivital** [comment] 2022-09-15 11:56
Hi @alexbakers, please make sure that you do not have any third-party libraries that override Mantine components styles. If that does not help, please provide a sandbox that reproduces the issue.

**Comment by alexbakers** [comment] 2022-09-15 12:52
> Hi @alexbakers, please make sure that you do not have any third-party libraries that override Mantine components styles. If that does not help, please provide a sandbox that reproduces the issue.

Thank you for your quick response.

<img width="276" alt="image" src="https://user-images.githubusercontent.com/98721968/190408442-8abf2b06-aad0-4707-877f-a96b3803c55d.png">

https://codesandbox.io/s/naughty-johnson-v5qzgx

**Comment by rtivital** [comment] 2022-09-15 14:34
Thanks for reproduction, the issue is fixed in 5.3.2

**Closed by rtivital** 2022-09-15 14:34 UTC
Labels: completed

**Comment by atumas-bananamilk** [comment] 2022-10-23 03:03
I've just noticed this update doesn't work correctly if `value` is an integer.
Previously, in the `5.1.5` update it accepted both integers & strings.
This broke some things for us before we found out.
Just an FYI.

**Comment by rtivital** [comment] 2022-10-23 08:30
It is correct behavior, SegmentedControl works only with strings as values
