### ISSUE TITLE
Number Input's parser and formatter is not working while running in production mode

### ISSUE THREAD

**Issue by deep1358** [mantinedev/mantine#2006] opened 2022-08-04 17:39 UTC
### What package has an issue

@mantine/core

### Describe the bug

Hello,
As I am using mantine in react app, but when I am using parser and formatter like below in  **NumberInput** tag:
```javascript
    <NumberInput
      name="amount"
      label="Amount"
      parser={(value) => value.replace(/\₹\s?|(,*)/g, '')}
      formatter={(value) =>
        !Number.isNaN(parseFloat(value))
          ? `₹ ${value}`.replace(/\B(?=(\d{3})+(?!\d))/g, ',')
          : '₹ '
      }
      min={1}
      {...form.getInputProps('amount')}
      required
      stepHoldDelay={500}
      stepHoldInterval={100}
      spellCheck={false}
      mt="md"
    />
```

It's working when I'm using it on a local server, but not working when I'm deploying the project on vercel platform.
So currently I'm unable to use this feature in production, so I have to use simple number formatter for that.
Please find the repo and deployed project link below:
[Github repo link](https://github.com/deep1358/Expense-Tracker-Frontend)
[Live demo](https://expense-tracker-frontend.vercel.app/addExpense)

### What version of @mantine/hooks page do you have in package.json?

4.2.12

### If possible, please include a link to a codesandbox with the reproduced problem

https://expense-tracker-frontend.vercel.app/addExpense

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

**Comment by esistgut** [comment] 2022-08-04 18:07
Your demo requires login, could it be a duplicate of the issue I reported just half an hour before this one? https://github.com/mantinedev/mantine/issues/2005

**Comment by deep1358** [comment] 2022-08-05 04:48
U only can login to the live website(link given above) while enabling all cookies, otherwise you won't be able to login

**Comment by rtivital** [comment] 2022-08-05 17:56
Please try updating to the latest version – I cannot reproduce the issue on mantine.dev website in production

**Comment by deep1358** [comment] 2022-08-06 10:58
As suggested when I upgrade to the latest version 5.0.3, getting errors like:
![image](https://user-images.githubusercontent.com/60952994/183245945-9a6b69b5-0ad2-4893-8e99-b2647d835372.png)

Tried deleting `.yarn`, `node_modules`, `.pnp.cjs`, `.pnp.loader.mjs`, and `yarn.lock`. 
After that cleared cache as well using the `yarn cache clear` command.
And then executed the `yarn` command.

But still getting errors.

**Comment by rtivital** [comment] 2022-08-06 11:40
You are required to install `@emotion/react` and `@emotion/server` packages

**Comment by deep1358** [comment] 2022-08-09 15:40
Hello, @rtivital as per your suggestion, I installed ```@emotion/react``` and ```@emotion/server``` packages,

Package.json look like this:

![image](https://user-images.githubusercontent.com/60952994/183696906-4c49a90d-c48c-4d64-a9f4-197fe82e184a.png)


But still getting the same error.

**Comment by rtivital** [comment] 2022-08-09 16:52
try removing node_modules folder, cleaning cache and reinstalling dependencies

**Comment by deep1358** [comment] 2022-08-09 18:38
I have tried everything, finally, by using PNPM, I was able to run.

But I am still getting the same error. However, I could increment/decrement numbers by the up/down arrow this time.

But still unable to type any value.

**Comment by rtivital** [comment] 2022-08-09 18:55
Can you try using yarn to install dependencies?

**Comment by deep1358** [comment] 2022-08-10 04:46
I have tried using npm ,yarn and now pnpm.

**Comment by rtivital** [comment] 2022-08-12 17:50
Have you tried deleting node_modules folder and reinstalling dependencies?

**Comment by deep1358** [comment] 2022-08-13 09:05
I have tried everything.

**Comment by rtivital** [comment] 2022-08-13 10:29
Well, I have no other ideas how to help in this case, you can use one of the templates as reference

**Comment by deep1358** [comment] 2022-08-13 11:16
Why don't you go to the live demo and try it yourself, and maybe you can figure out the issue? 
[Demo](https://expense-tracker-frontend.vercel.app/addExpense). Login with a google account (Use chrome only), then go to the add Expense page, where you'll find the issue.

**Comment by rtivital** [comment] 2022-08-13 11:21
I cannot debug the issue that is not reproducible in any of the provided templates

**Comment by deep1358** [comment] 2022-08-13 12:54
You can see in the Github code as well as the demo that I have written the code exactly as described in provided templates.
Not sure what's the issue.

**Comment by rtivital** [comment] 2022-08-13 17:37
Sorry, I cannot spend too much time on it, if you can reproduce the issue in one of the templates I can have a look, otherwise the issue most likely is not with Mantine but with your setup.

**Comment by rtivital** [comment] 2022-08-18 11:56
@deep1358 if you can provide a minimal reproducible example using one of the templates, then feel free to reopen the issue.

**Closed by rtivital** 2022-08-18 11:56 UTC

**Comment by deep1358** [comment] 2022-08-18 12:54
Okay, thanks for your support.

**Comment by msiric** [comment] 2023-11-17 17:11
@deep1358 How did you get the value to format on change (using Mantine V6)?
In their docs the component only updates on blur.
