### ISSUE TITLE
DatePicker doesn't immediately update UI when `locale` prop changes

### ISSUE THREAD

**Issue by akd-io** [mantinedev/mantine#3418] opened 2023-01-25 09:57 UTC
### What package has an issue

@mantine/dates

### Describe the bug

When changing the `locale` prop of the Mantine [DatePicker](https://mantine.dev/dates/date-picker/), the DatePicker doesn't re-render to change the value. Only once the DatePicker is clicked, does its UI update.

### What version of @mantine/hooks page do you have in package.json?

^5.10.1

### If possible, please include a link to a codesandbox with the reproduced problem

[CodeSandbox](https://codesandbox.io/s/affectionate-khayyam-pk73fl?file=/src/App.tsx)

You'll notice you'll need to either click the DatePicker, for change its value for the locale change to take effect.

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

**Comment by rtivital** [comment] 2023-01-25 09:58
Please provide a sandbox that reproduces the issue, template – https://codesandbox.io/s/mantine-template-9ze89?file=/src/App.tsx:0-6

**Comment by akd-io** [comment] 2023-01-25 10:09
Update with [CodeSandbox link](https://codesandbox.io/s/affectionate-khayyam-pk73fl?file=/src/App.tsx)

**Comment by rtivital** [comment] 2023-01-25 10:12
Thanks for reporting, the issue will be fixed in 6.0

**Comment by rtivital** [comment] 2023-01-27 07:17
The issue is fixed in 6.0, it will be available in next `6.0.0-alpha.1` release

**Comment by rtivital** [comment] 2023-03-03 06:49
Fixed in 6.0

**Closed by rtivital** 2023-03-03 06:49 UTC
Labels: completed-in-6.0
