### ISSUE TITLE
DateTimePicker sets seconds to `new Date()` when updating time value, when `withSeconds` is not specified

### ISSUE THREAD

**Issue by samcarton** [mantinedev/mantine#4737] opened 2023-09-07 06:11 UTC
### What package has an issue

@mantine/dates

### Describe the bug

- Using `DateTimePicker`,  and `withSeconds={false}`
- Put console log on the `onChange`
- Select a date and an hour/minute time
- Notice that the date being selected has seconds equal to `new Date()` seconds (i.e. the current times' seconds)
- I would expect the seconds to default to zero

### What version of @mantine/hooks page do you have in package.json?

6.0.19

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Possible fix

https://github.com/mantinedev/mantine/blob/0455a0f3c47938c0dcae69e5093ce6c28a6bc73b/src/mantine-dates/src/components/DateTimePicker/DateTimePicker.tsx#L129

Change ☝️  to `seconds === undefined ? timeDate.setSeconds(0) : timeDate.setSeconds(seconds);`

**Comment by rtivital** [comment] 2023-09-25 13:11
The issue is resolved in [7.0.1](https://github.com/mantinedev/mantine/releases/tag/7.0.1)

**Closed by rtivital** 2023-09-25 13:11 UTC
Labels: Completed patch

**Comment by samcarton** [comment] 2023-10-01 09:05
can we get a fix for 6.X ? 7 is majorly breaking for us
