### ISSUE TITLE
Tooltips and transactions not working on Chrome (Debian)

### ISSUE THREAD

**Issue by n37sn4k3** [mantinedev/mantine#3378] opened 2023-01-16 13:17 UTC
Tooltip and Transaction Mantine components not taking effect on Chrome/Chromium, OS Linux Debian.

**Comment by n37sn4k3** [comment] 2023-01-16 13:18
v5.10.0

**Comment by rtivital** [comment] 2023-01-16 15:45
Mantine does not export Transaction component

**Comment by rtivital** [comment] 2023-01-17 06:36
Duplicate of #3382

**Closed by rtivital** 2023-01-17 06:36 UTC
