### ISSUE TITLE
Popup with `closeOnEscape` does not call `onClose`

### ISSUE THREAD

**Issue by DreierF** [mantinedev/mantine#7019] opened 2024-10-24 05:32 UTC
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.13.4

### What package has an issue?

@mantine/core

### What framework do you use?

Vite

### In which browsers you can reproduce the issue?

All

### Describe the bug

A controlled `Popup` with `closeOnEscape` enabled did call `onClose` when ESC was pressed, while the popup was showing in version prior to 7.13.3. This is no longer the case and hence corresponding popups that don't have `closeOnClickOutside` enabled can't be closed anymore.

### If possible, include a link to a codesandbox with a minimal reproduction

https://codesandbox.io/p/sandbox/mantine-popover-bug-forked-tqqzlh?workspaceId=070a61c6-ddaf-4216-be57-565e612ba63f

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment] 2024-10-24 08:28
It is intended behavior, starting from 7.13.4. `onClose` prop is called when the dropdown is closed (`opened` prop changed to `false`), not when something triggers closing dropdown. To fix the issue, use `onChange` handler instead – https://codesandbox.io/p/sandbox/mantine-popover-bug-forked-9ftkqc?file=%2Fsrc%2FApp.tsx%3A7%2C11

The change is related to other bug fixes and cannot be implemented other way.

**Closed by rtivital** 2024-10-24 08:28 UTC

**Comment by gl3nn** [comment] 2024-10-28 17:19
@rtivital will this also become the behavior for Modals? 

In our project we always pass in a callback into `onClose` to change the controlled value (that gets passed into `opened`). We do the same for `Modal`. There it seems to still work as expected, but for `Popover` this no longer works. (And is explained by your comment.)

Would be nice to have this standardized then (and have the same behavior for Modal). I do think this is quite breaking behavior of the `onClose` prop. We have to change 100+ popovers to the `onChange` method, which seems quite intense for a patch release.

**Comment by rtivital** [comment] 2024-10-28 17:33
No, this change does not impact Modal and Drawer components, they use different logic. Popover can be controlled and uncontrolled – it provides onChange prop. Modal/Drawer can only be controlled – they provide only onClose prop.

**Comment by gl3nn** [comment] 2024-10-28 17:35
Thank you for your fast reply!

**Comment by radulescuandrew** [comment] 2024-12-23 12:38
@rtivital I have the following setup:

1. Controller Popover
2. Closed on: (a) clicking a button inside the popover, (b) clicking again on target, (c) clicking outside
3. Using `useClickOutside` for the (c) option and to ignore the click on the target. 

 Using `nodes` param in `useClickOutside` will close the popover when I click inside the Popover. The click is considered outside. I can give the same HTML Element a different id and add it in the nodes array, but it defies the purpose. 

Am I missing something? Thanks!
