### ISSUE TITLE
Issue with left handle of RangeSlider when `min` prop is set to a negative value

### ISSUE THREAD

**Issue by snehilvj** [mantinedev/mantine#2897] opened 2022-11-06 18:50 UTC
### What package has an issue

@mantine/core

### Describe the bug

Left handle of RangeSlider is not draggable if `min` prop is set to a negative value.
![rangeslider-mantine](https://user-images.githubusercontent.com/91216500/200189386-ccf143f1-98c9-4a32-8f86-16f4ae65c99c.gif)

### What version of @mantine/hooks page do you have in package.json?

5.7.1

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/clever-dhawan-ly7qy0

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

**Comment by rtivital** [comment] 2022-11-06 19:46
@wes337 was this caused by your changes? Maybe we should just rollback your PRs?

**Comment by wes337** [comment] 2022-11-07 06:28
> @wes337 was this caused by your changes? Maybe we should just rollback your PRs?

I have tried reverting any change I made to the Slider, but it does not fix this issue.

You can see for yourself by changing the code of the `get-change-value.ts` file back to the original from this PR: https://github.com/mantinedev/mantine/pull/2656/files. Reverting those changes to the `getChangeValue` function is the same as rolling back my PRs (the other changes were only Storybook stories).

**Comment by wes337** [comment] 2022-11-07 06:43
I have also tried rolling back Mantine to as early as 5.5.0 and the problem persists.

@snehilvj , your issue can be fixed by adding the `minRange` prop.

**Comment by rtivital** [comment] 2022-11-07 06:45
Okay, I'll have a look then

**Comment by wes337** [comment] 2022-11-07 07:14
I was able to fix this issue by making some changes to the `setRangedValue` function in the `RangeSlider` component:

![image](https://user-images.githubusercontent.com/9464690/200247005-a51e5c36-66c1-4659-8cf4-5df33ff76f34.png)

**Comment by rtivital** [comment] 2022-11-12 11:22
Fixed in 5.7.2

**Closed by rtivital** 2022-11-12 11:22 UTC
Labels: completed
