### ISSUE TITLE
Anchor doesn't display underline after upgrading to v6

### ISSUE THREAD

**Issue by lgaspari** [mantinedev/mantine#4209] opened 2023-05-08 17:44 UTC
### What package has an issue

@mantine/core

### Describe the bug

Hey there!

It looks like the `Anchor` styles changed from v5 to v6 and now you cannot see the underline unless you hover the link.

Here's a comparison:
- [v5](https://codesandbox.io/s/vigorous-snyder-x7qiur?file=/src/App.tsx): underline is visible by default (even if hovered)
- [v6](https://codesandbox.io/s/beautiful-brahmagupta-pyf3fg?file=/src/App.tsx): underline is not visible by default anymore (only if hovered)

Recently, It was reported that the `underline=false` wasn't removing the underline when hovering as expected (#3654), however that behavior is still different than the v5 and it wasn't logged in the [Version 6.0.0 changelog](https://mantine.dev/changelog/6-0-0/).

I guess my concern is, what's the expected behavior for the Anchor? I've worked on a fix that reverts some of these changes as it was in v5, but I wonder this might break other's people code as they were using it as-is. Here's the commit https://github.com/lgaspari/mantine/commit/4e3a118a593a0558f761616f66b565c9015c4b86

If the idea is to keep current behavior, then I think the docs (either prop docs and version 6 changelog) should be updated the reflect the fact that `underline` doesn't work as v5, but instead it controls whether to show the underline when hovering the anchor.

### What version of @mantine/hooks page do you have in package.json?

6.0.8

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/beautiful-brahmagupta-pyf3fg?file=/src/App.tsx

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Possible fix

a) Update docs to reflect v6 changes; or
b) Revert to v5 changes; or
c) Add new prop `underlineOnHover` to control whether to show the underline when hover and leave `underline` just for the not hover use case

**Comment by rtivital** [comment] 2023-09-21 19:20
The issue is fixed in 7.0

**Closed by rtivital** 2023-09-21 19:20 UTC
