### ISSUE TITLE
Carousel.Item doesn't have spacing between other items

### ISSUE THREAD

**Issue by danestves** [mantinedev/mantine#2396] opened 2022-09-08 16:32 UTC
### What package has an issue

@mantine/core

### Describe the bug

From the `5.2.7` release that introduce this fix https://github.com/mantinedev/mantine/pull/2336 now the items doesn't have any spacing between

![CleanShot 2022-09-08 at 12 30 47](https://user-images.githubusercontent.com/31737273/189176529-dde3c5b8-daa8-446f-90e7-4ebe4f1c399a.png)

### What version of @mantine/hooks page do you have in package.json?

5.2.7

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

**Comment by rtivital** [comment] 2022-09-08 16:48
Thanks for reporting, the issue will be fixed in next patch

**Comment by danestves** [comment] 2022-09-08 20:12
Thank you! I'm still new with the core code of Mantine, hope in a future be available to understand and make features and fixes for the library :D

**Comment by italodeandra** [comment] 2022-09-08 22:58
@rtivital Did you already found the problem? This problem seems weird. If you didn't investigate yet I will.

**Comment by rtivital** [comment] 2022-09-09 04:57
Yes, it is caused by the change in PR, you can check out the same issue here in final slide – https://mantine.dev/others/carousel/#size-and-gap 

I've reverted your PR for now

**Comment by rtivital** [comment] 2022-09-09 10:52
Fixed in 5.3.0

**Closed by rtivital** 2022-09-09 10:52 UTC
Labels: completed
