### ISSUE TITLE
Error: Invalid value for <svg> attribute width="1rem"

### ISSUE THREAD

**Issue by vaynevayne** [mantinedev/mantine#4015] opened 2023-04-06 02:24 UTC
### What package has an issue

@mantine/core

### Describe the bug

`safari 版本15.6.1 (17613.3.9.1.16)`

<img width="1415" alt="image" src="https://user-images.githubusercontent.com/124666577/230256549-ed21b6b4-c9de-4548-9943-d978b4f9ca10.png">

### What version of @mantine/hooks page do you have in package.json?

6.0.2

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by rtivital** [comment] 2023-04-06 05:10
Duplicate of https://github.com/mantinedev/mantine/issues/3699

**Closed by rtivital** 2023-04-06 05:10 UTC
Labels: review required
