### ISSUE TITLE
Unable to set ID on Select component in v7

### ISSUE THREAD

**Issue by matt-greenfield-15** [mantinedev/mantine#4809] opened 2023-09-20 11:09 UTC
## Steps to reproduce 
- [Got to https://codesandbox.io/s/mantine-select-input-id-issue-dyggmf](https://codesandbox.io/s/mantine-select-input-id-issue-dyggmf?file=/src/App.tsx)
- Observe that the ID in the HTML, is not the same as the ID prop being set in the JSX
- Downgrade packages to Mantine V6 and observe that the ID matches

## Why it matters
I'd imagine for most uses cases this is not an issue. But I'm using my own InputWrapper component and [as per these instructions](https://mantine.dev/core/input#accessibility) I set an ID on both the label and the input.
The issue means my label `for` and input `id` do not match.

## Possible fix
It could be that we just need to first check the prop here before creating the new id. Something like `const _id = id || useId();`
https://github.com/mantinedev/mantine/blob/d41e95a1ecb704628164194bcaa19c2fea263682/src/mantine-core/src/components/Select/Select.tsx#L127

**Comment by mateuscqueiros** [comment] 2023-09-21 02:52
After some digging, I found out that the useId() hook (coming from @mantine/hooks) can receive a parameter with a static id that may or may not be undefined. If no parameter is set or the id is undefined, it returns a mantine-generated id and that was causing this issue in the Select (no static id was being passed to the hook). Also, there were some other components using the function useId coming from React which does not accept any parameters. I'm submitting a PR with these fixes in a second :)

**Comment by rtivital** [comment] 2023-09-25 13:10
The issue is resolved in [7.0.1](https://github.com/mantinedev/mantine/releases/tag/7.0.1)

**Closed by rtivital** 2023-09-25 13:10 UTC
Labels: Completed patch

**Comment by matt-greenfield-15** [comment] 2023-09-25 14:03
Thank you both!

**Comment by bayerlse** [comment] 2024-12-13 13:14
It seems that in 7.13.2 its not working. When setting a custom on ID on TextArea Component, it uses a mantine id instead:

mantine-rt4zdbr0s-target
