### ISSUE TITLE
Wrong focus error style for input elements v7

### ISSUE THREAD

**Issue by wuifdesign** [mantinedev/mantine#4832] opened 2023-09-21 21:35 UTC
### What package has an issue

@mantine/core

### Describe the bug

Using the v7 version the behavior or input element error state changed. the border doesn't stay red if focused.

**v6**

![Screenshot 2023-09-21 233142](https://github.com/mantinedev/mantine/assets/5678318/24e24869-e7c2-4f11-babd-de5f167e8fee)

**v7**

![Screenshot 2023-09-21 233127](https://github.com/mantinedev/mantine/assets/5678318/27297e74-3cf0-45a2-872b-bbfc214e5cd0)

can be checked here: https://mantine.dev/core/text-input/#error-state vs https://v6.mantine.dev/core/text-input/#invalid-state-and-error

### What version of @mantine/* page do you have in package.json? (Note that all @mantine/* packages must have the same version in order to work correctly)

7.0.0

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by rtivital** [comment] 2023-09-25 13:10
The issue is resolved in [7.0.1](https://github.com/mantinedev/mantine/releases/tag/7.0.1)

**Closed by rtivital** 2023-09-25 13:10 UTC
Labels: Completed patch
