### ISSUE TITLE
Examples using "import {} from '@tabler/icons'" instead of "@tabler/icons-react"

### ISSUE THREAD

**Issue by Technoblqde** [mantinedev/mantine#3558] opened 2023-02-15 19:25 UTC
### Link to the page where something nasty is located

https://ui.mantine.dev/category/app-cards

### Exact quote of what is wrong

@tabler/icons no longer works with Next.js for example, instead you must use @tabler/icons-react.

This is confusing. I'd hope you could fix this in some way. Thanks.

### Are you willing to create pull request with the fix?

None

**Comment by rtivital** [comment] 2023-02-15 19:52
Duplicate of #3415

**Closed by rtivital** 2023-02-15 19:52 UTC
Labels: review required
