### ISSUE TITLE
Selecting on MultiSelector throws an error when width is not set

### ISSUE THREAD

**Issue by thiagoschreck** [mantinedev/mantine#5390] opened 2023-12-08 17:28 UTC
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.3.1

### What package has an issue?

@mantine/core

### What framework do you use?

create-react-app (CRA)

### In which browsers you can reproduce the issue?

Not applicable – issue is not related to the browser

### Describe the bug

When selecting or de-selecting a value in a MultiSelect component, the following error is thrown:
![image](https://github.com/mantinedev/mantine/assets/56611782/83e509e5-520d-4781-bd3e-aa8074d27668)

The code is as follows
```javascript
 const personal: ComboboxItem[] = (personalJSON as Personal[]).map((personal) => {
     return {
         value: JSON.stringify(personal),
         label: personal.nombre,
     }
 })
<MultiSelect
        label="Personal que la realizó"
        data={personal}
        nothingFoundMessage="No hay resultados"
        placeholder="Personal"
        onChange={(event) => form.setFieldValue("personal", [...form.values.personal, ...event.map(p => JSON.parse(p))])}
        clearable
 />
```
The error doesn't appear if the width is set for the element (tested it with the "w" props).

I tried recreating it in codesandbox.io but I couldn't. I tested it on Chrome and Edge and the error happens on both.

**Comment by rtivital** [comment] 2023-12-09 13:33
Duplicate of #4268

**Closed by rtivital** 2023-12-09 13:33 UTC

**Comment by gemasaputera** [comment] 2024-06-24 23:22
hi there, i've been facing that issue today, how do you solve that ? I'm using `"@mantine/core": "^7.4.0"` , `"react": "^18.2.0"`

**Comment by rtivital** [comment] 2024-06-25 02:29
Try updating dependencies to the latest version

**Comment by gemasaputera** [comment] 2024-06-25 02:53
So i just ```
npm i @mantine/core
``` to fix this?

**Comment by rtivital** [comment] 2024-06-25 03:14
https://help.mantine.dev/q/how-to-update-dependencies

**Comment by dionysis9901** [comment] 2024-09-23 10:29
> https://help.mantine.dev/q/how-to-update-dependencies

It didn't help in my case.I am using MultiSelect in the Group component , and still getting this error
