### ISSUE TITLE
V6 SVG new rem convertor problem

### ISSUE THREAD

**Issue by specOper99** [mantinedev/mantine#3699] opened 2023-03-06 10:52 UTC
### What package has an issue

@mantine/core

### Describe the bug

whenever any `<svg/>` is rendered the size is being converted to rem which produce an error

> Error: Invalid value for <svg> attribute width="2.25rem"

Casue the SVG must be always given pixels

### What version of @mantine/hooks page do you have in package.json?

6.0.0

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by eugeniudedin** [comment] 2023-03-08 01:54
I have same issue on svg used in components by default not custom. Example when button has loading status, 'rem' error appeare for spinner svg element.

**Comment by ericschmar** [comment] 2023-03-08 16:25
I also have the same issue. I'm using Orion Version 0.99.123.3-beta (WebKit 615.1.16.1) and have this issue. I understand it's a lesser known browser, but it's built off WebKit, and I suspect Safari  has a similar problem.

**Comment by specOper99** [comment] 2023-03-08 17:20
Actually YES, @rtivital it is working correctly but the error message still exists in the browser console
And YES, @ericschmar I am using safari to confirm your suspicion

**Comment by edouard-wttj** [comment] 2023-03-09 12:36
indeed same issue: error message on Safari

**Comment by 7iomka** [comment] 2023-03-11 11:39
I think, if a component or a wrapper for an svg element in mantine codebase will have font-size, as a workaround will be to set dimensions through width/height attributes on svg in `em` units relative to this font size. Set with em works as expected (supported by spec 1.1)

**Comment by elibroftw** [comment] 2023-04-10 23:17
So then would this be something to report upstream to the Firefox team?

**Comment by jgravois** [comment] 2023-04-24 05:59
> So then would this be something to report upstream to the Firefox team?

I don't think so. my understanding is that the browsers are logging an error because the SVG 1.1 spec explicitly disallows rem units as width/height attributes.

reference:
https://bugzilla.mozilla.org/show_bug.cgi?id=1231147
https://caniuse.com/?search=svg

**Comment by rtivital** [comment] 2023-09-19 07:06
This issue is closed for one of these reasons:

- It was fixed in 7.0
- It is no longer reproducible in 7.0
- It is no longer applicable in 7.0
- It does not have a reproduction

If you think that this issue was closed by mistake, and it is still an issue in version 7.0, please reopen it.

**Closed by rtivital** 2023-09-19 07:06 UTC
