### ISSUE TITLE
Switch component does not show Tooltip on hover

### ISSUE THREAD

**Issue by DJWalker42** [mantinedev/mantine#4757] opened 2023-09-13 10:49 UTC
### What package has an issue

@mantine/core

### Describe the bug

Switch component does not show the Tooltip on mouseover/hover. It will show it on a focus event if you explicitly set that property to be true but then partially covers the switch (and is not the desired behaviour).

Note that in codesandbox the latest version of mantine is 6.0.5 but this also occurs in v6.0.20 that I've got in my package.json

### What version of @mantine/hooks page do you have in package.json?

6.0.20

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/mantine-playground-forked-3klgyf?file=/src/App.tsx

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

**Comment by rtivital** [comment] 2023-09-19 06:59
The issue is fixed in 7.0:

```tsx
<Tooltip label="Tooltip" refProp="rootRef" position="bottom-start">
  <Checkbox label="With tooltip" defaultChecked />
</Tooltip>
```

**Closed by rtivital** 2023-09-19 06:59 UTC
Labels: Fixed in 7.0
