### ISSUE TITLE
DatePickerInput validation broken on Safari

### ISSUE THREAD

**Issue by KevinLu** [mantinedev/mantine#4455] opened 2023-06-23 17:58 UTC
### What package has an issue

@mantine/dates

### Describe the bug

I compared using Mantine 5.10.5 and v6 using the DatePicker (DatePickerInput on v6) component. I'm using a very standard setup with `react-hook-form` and made two codesandboxes with Mantine v5 and v6 to showcase the difference.

On Chrome (v5 and v6), the error message shows up. On Safari, the error message only shows up with Mantine v5.

Steps:
1. Pick any date with the DatePicker component
2. Observe the error message (the yup validation is hardcoded to always error)

My exact environment is Safari Version 16.5 (18615.2.9.11.4) on MacOS 13.4.

v5: https://codesandbox.io/s/sparkling-silence-c6dtny?file=/src/App.js
v6: https://codesandbox.io/s/competent-goodall-jt67z4?file=/src/App.js

### What version of @mantine/hooks page do you have in package.json?

6.0.5

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/competent-goodall-jt67z4?file=/src/App.js

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

### Possible fix

The `fieldState` from `react-hook-form` always says `onTouched` is false with Mantine v6, but it's set properly with Mantine v5. If the component can respond to this properly, it might fix the issue.

Found this (maybe) relevant bug on Safari: https://bugs.webkit.org/show_bug.cgi?id=22261

**Comment by frec-kenneth** [comment] 2023-07-13 18:08
The DatePickerInput is a button, and Safari handles focus states of buttons differently[1]. It does not focus the button when you click it. Since the button does not focus, it cannot blur, and so the blur event does not trigger your validation.

You can manually focus the button on click like this:
```js
                onClick={(e) => {
                  e.target.focus();
                }}
```
and then the blur should trigger the validation as you'd expect.

I think it would be great if Mantine could workaround this, or even just mention it in the docs for the DatePickerInput, because the problem is not obvious.

[1] https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button#clicking_and_focus

**Comment by rtivital** [comment] 2023-09-19 18:59
It is not planned to be fixed on the library level – this functionality depends on the user OS settings.

**Closed by rtivital** 2023-09-19 18:59 UTC
