### ISSUE TITLE
SegmentedControl in a Modal

### ISSUE THREAD

**Issue by johansunden** [mantinedev/mantine#5647] opened 2024-01-26 14:20 UTC
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.4.2

### What package has an issue?

@mantine/core

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

Chrome

### Describe the bug

Whenever I use a SegmentedControl in a Modal it looks a bit collapsed until I interact with it, at which point it falls into place. (Or rather the default selected control is higher than it should be.)

<img width="526" alt="image" src="https://github.com/mantinedev/mantine/assets/920071/13bea1c7-1eed-424d-ab22-4ec6da734cd7">

<img width="516" alt="image" src="https://github.com/mantinedev/mantine/assets/920071/7fd16156-acfa-4028-94c9-becd67f72df4">

Anyone else seen this?

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment] 2024-01-26 16:28
Duplicate of https://github.com/mantinedev/mantine/issues/3330

**Closed by rtivital** 2024-01-26 16:28 UTC
