### ISSUE TITLE
Dropdown Issue in ComboBox Styles API section

### ISSUE THREAD

**Issue by JawHawk** [mantinedev/mantine#4845] opened 2023-09-22 18:10 UTC
### Link to the page where something nasty is located

https://mantine.dev/core/combobox/#without-dropdown

### Exact quote of what is wrong

https://github.com/mantinedev/mantine/assets/86140365/049f957c-383b-4519-8e93-2e68c3e7b32e

The dropdown of section 'Styles API' which is below  'Without Dropdown' Section, is overlapping above and making it difficult to read the 'without dropdown' section. 

### Are you willing to create pull request with the fix?

Yes

**Comment by rtivital** [comment] 2023-09-25 13:10
The issue is resolved in [7.0.1](https://github.com/mantinedev/mantine/releases/tag/7.0.1)

**Closed by rtivital** 2023-09-25 13:10 UTC
Labels: Completed patch
