### ISSUE TITLE
Modale Dialog clips DateTimePicker Popup Layer

### ISSUE THREAD

**Issue by aheissenberger** [mantinedev/mantine#4224] opened 2023-05-11 15:20 UTC
### What package has an issue

@mantine/dates

### Describe the bug

The popup layer with calendar and time input is clipped by the modal dialog borders
![SCR-20230511-peyt](https://github.com/mantinedev/mantine/assets/200095/e2e33f8d-0ec5-451f-a6b5-41965ca9d7f5)

### What version of @mantine/hooks page do you have in package.json?

6.0.10

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/patient-snowflake-wkbx8h

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

**Comment by yverby** [comment] 2023-05-11 15:35
Duplicate of https://github.com/mantinedev/mantine/issues/4100
Check it to fix your issue

**Comment by rtivital** [comment] 2023-05-12 04:47
https://codesandbox.io/s/agitated-tharp-5esd2o

**Closed by rtivital** 2023-05-12 04:47 UTC

**Comment by rubek-joshi** [comment] 2023-05-18 04:14
> https://codesandbox.io/s/agitated-tharp-5esd2o

This needs to be in the documentation. Putting date pickers in modal are a common occurrence.
