### ISSUE TITLE
Mantine min allows for negative inputs

### ISSUE THREAD

**Issue by owenmoogk** [mantinedev/mantine#7016] opened 2024-10-23 06:52 UTC
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.13.2

### What package has an issue?

@mantine/core

### What framework do you use?

Vite

### In which browsers you can reproduce the issue?

Chrome

### Describe the bug

In a mantine number input, set the min to 10. Then, type in "0-8". Notice how the field goes to -8, even though it shouldn't.
![image](https://github.com/user-attachments/assets/e04a0cd0-7606-4502-8eeb-e1514664b61c)

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment] 2024-10-23 07:28
Duplicate of https://github.com/mantinedev/mantine/issues/7005

**Closed by rtivital** 2024-10-23 07:28 UTC
