### ISSUE TITLE
useMantineColorScheme causes component to be rendered twice 

### ISSUE THREAD

**Issue by c0nd3v** [mantinedev/mantine#5584] opened 2024-01-17 13:44 UTC
### Describe the bug

For some reason, if I am using useMantineColorScheme, it makes my component render twice for seemingly no reason when the page loads.

(If I’m using StrictMode, the component will render 4 times in total. So the problem is not StrictMode)

**Comment by rtivital** [comment] 2024-01-17 15:07
Duplicate of #5575

**Closed by rtivital** 2024-01-17 15:07 UTC
Labels: Duplicate

**Comment by c0nd3v** [comment] 2024-01-17 19:27
Just tested it on 7.4.2, it's not fixed.

**Comment by c0nd3v** [comment] 2024-01-17 19:32
Okay sure
