### ISSUE TITLE
Slider onChange callback can't see states of calling component

### ISSUE THREAD

**Issue by ginfonic** [mantinedev/mantine#3250] opened 2022-12-28 08:42 UTC
### What package has an issue

@mantine/core

### Describe the bug

In Slider component when you use a custom callback in onChange prop that not only set a value but also uses internal states of calling component these states are invisible, undefined or 0.
The other Mantine components, Select for instance or the standard ones (input) can see calling component states in callback normally as it should be.
I hope it's a bug not a feature.

<img width="851" alt="Снимок экрана 2022-12-28 в 11 36 12" src="https://user-images.githubusercontent.com/537747/209783500-54ccccc1-7eea-4a77-b4e6-65eaeaded0f9.png">

<img width="864" alt="log" src="https://user-images.githubusercontent.com/537747/209782911-cdad06ac-4a4f-4a0c-95f0-cbf1b83d474c.png">

### What version of @mantine/hooks page do you have in package.json?

5.9.5

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by rtivital** [comment] 2022-12-28 10:41
Slider onChange function is momoized to improve performance, it cannot reference state variables.

**Comment by frustak** [comment] 2023-01-10 08:48
I've found a workaround, you can use this component instead if memoization is making issues:
```ts
import { Slider, SliderProps } from '@mantine/core'
import { useDidUpdate } from '@mantine/hooks'

function SliderNoMemo(props: SliderProps) {
	const [value, setValue] = useState(props.value)

	useDidUpdate(() => {
		if (value) props.onChange?.(value)
	}, [value])

	useDidUpdate(() => {
		setValue(props.value)
	}, [props.value])

	return <Slider {...props} value={value} onChange={setValue} />
}
```

**Comment by rtivital** [comment] 2023-01-17 06:53
Duplicate of #2840

**Closed by rtivital** 2023-01-17 06:53 UTC

**Comment by tscans** [comment] 2023-01-28 20:01
> ```ts
> import { Slider, SliderProps } from '@mantine/core'
> import { useDidUpdate } from '@mantine/hooks'
> 
> function SliderNoMemo(props: SliderProps) {
> 	const [value, setValue] = useState(props.value)
> 
> 	useDidUpdate(() => {
> 		if (value) props.onChange?.(value)
> 	}, [value])
> 
> 	useDidUpdate(() => {
> 		setValue(props.value)
> 	}, [props.value])
> 
> 	return <Slider {...props} value={value} onChange={setValue} />
> }
> ```

Not ideal but this worked and helped me. Thanks!
