### ISSUE TITLE
Problem with the components' visualization when accessing to a tab directly

### ISSUE THREAD

**Issue by Knamer95** [mantinedev/mantine#1510] opened 2022-05-24 17:02 UTC
### Link to the page where something nasty is located

https://mantine.dev/core/checkbox/?t=props

### Exact quote of what is wrong

When accessing to the component view, everything works fine, but if you go to a tab ('Component props' or 'Styles API') and then refresh the page, this happens:

![image](https://user-images.githubusercontent.com/59671002/170089484-48b643ec-6010-498a-b038-6a33d1f022cb.png)

Same thing happens if you access to the tab directly from the URL.

I tested this on desktop (Chrome v101.0.4951.67 and Firefox v100.0.2), and got a 100% reproduction rate. Happens on every component.

Please let me know if you need any extra clarification or help! 😃

**Comment by rtivital** [comment] 2022-05-24 17:32
The issue is already fixed in v5 branch, it will be released with 5.0

**Closed** 2022-05-24 17:46 UTC
