### ISSUE TITLE
Select has wrong behavior when tab key is pressed

### ISSUE THREAD

**Issue by LucasLemanowicz** [mantinedev/mantine#693] opened 2022-01-17 18:56 UTC
### What package has an issue

@mantine/core

### Describe the bug

When filling out forms, users often will press the tab key when the right item is selected to move onto the next field. This seems to be broken as shown below:

https://user-images.githubusercontent.com/361348/149823381-11f8e95b-015f-4c7d-b7bf-6bfece089aa9.mov

Repro:
* Click on the first Select box
* Type a letter, and press tab
* Repeat for second Select, etc.

### In which browser did the problem occur

Chrome

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/charming-jang-l9jqp?file=/src/App.tsx

### Do you know how to fix the issue

No

### Possible fix

The correct behavior should be that as a user is typing, the active item selection should be updated in the list (regardless of what the `filter` function is set to. When a person tabs out or leaves the field, if there is a valid full or partial match, the last active item is selected. If the string entered is not a partial or complete match, the last valid item should be selected.

Example:

Select input with `[Alice, Alfred, Bob, Carol]` and `Carol` is selected (from before)
User types "A" -> list filters down to `[Alice, Alfred]` and `Alice` is highlighted.
_If user tabs or clicks out at this point, `Alice` will be selected_

User continues typing "ALF", list filters down to `[Alfred]` and `Alfred` is highlighted.
_If user tabs or clicks out at this point, `Alfred` will be selected_

User continues typing "ALFASDFASDFSADF", list filters down to `[]` and nothing is highlighted.
_If user tabs or clicks out at this point, `Carol` (from last valid selection) will remain selected_

**Comment by rtivital** [comment] 2022-01-17 19:32
I am not convinced that current behavior is incorrect, user should explicitly select value to fill select field. Maybe `selectOnBlur` is broken in your specific case, but I doubt that we should handle that on library level. For your example, I would consider using a controlled Autocomplete instead with validation of input on your side.

**Comment by LucasLemanowicz** [comment] 2022-01-17 20:09
In case it's helpful, here's a compilation of how a few other popular libraries (React Select, React Bootstrap, Blueprint Select) handle this:

https://codesandbox.io/s/eager-christian-gihgf?file=/src/App.tsx

React Select seems to have one of the more intuitive ways of handling user input.

**Comment by LucasLemanowicz** [comment] 2022-01-17 20:22
Ok to narrow down the scope, it seems like the main issue I'm having is with having both `selectOnBlur={true}` AND `filter={() => true}` being set at the same time.

**Comment by wes337** [comment] 2022-03-26 06:15
I could take this issue if you'd like. I have been reading the best practices from W3 here: https://www.w3.org/TR/wai-aria-practices-1.1/examples/combobox/aria1.1pattern/listbox-combo.html

It does seem to be missing this:
> The automatically selected suggestion becomes the value of the textbox when the combobox loses focus unless the user chooses a different suggestion or changes the character string in the textbox.

Additionally, there is missing keyboard support for `Home` or `End` keys, which should move the focus to the beginning or end of the list.

**Comment by rtivital** [comment] 2022-03-26 06:47
We already have `selectOnBlur` prop, so there is no need to add that. 
`Home` and `End` keys are fine, you can add them with a PR

**Comment by wes337** [comment] 2022-03-26 07:15
Oh yeah you're right, I missed that prop. And I'm now re-reading this issue, and I don't understand the problem. Seems to be working exactly as intended, including in the provided Codesandbox.

**Comment by rtivital** [comment] 2022-03-27 11:17
Alright, I think I will not be fixing it, as the issue seems very situational or may be already fixed with one of the releases

**Closed by rtivital** 2022-03-27 11:17 UTC
