### ISSUE TITLE
Unable to resolve module @mantine/form

### ISSUE THREAD

**Issue by imsaha** [mantinedev/mantine#4866] opened 2023-09-25 08:21 UTC
### What package has an issue

@mantine/form

### Describe the bug

Using in react-native expo project the package is unable to resolve when running on IOS or Android, but works as expected on the web.

![image](https://github.com/mantinedev/mantine/assets/34410962/8b749733-9796-4366-8ac2-9ca96ebe5a74)

### What version of @mantine/* page do you have in package.json? (Note that all @mantine/* packages must have the same version in order to work correctly)

7.0.0

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by rtivital** [comment] 2023-09-25 13:09
The issue is resolved in [7.0.1](https://github.com/mantinedev/mantine/releases/tag/7.0.1)

**Closed by rtivital** 2023-09-25 13:09 UTC
Labels: Completed patch
