### ISSUE TITLE
 ModalProvider: `onClose` causing Type Error before opening any modal

### ISSUE THREAD

**Issue by dimbslmh** [mantinedev/mantine#5577] opened 2024-01-16 06:29 UTC
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.4.1

### What package has an issue?

@mantine/modals

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

Chrome

### Describe the bug

 ModalProvider: `onClose` causing Type Error before opening any modal.
 Esc key triggers onClose without an id.
 Not sure if it's caused by `trapFocus: false` only.. But you'd expect onClose only to closeModal when an id is available.

https://github.com/mantinedev/mantine/blob/703bf447b1a751daee7f3c2fff9c418bd13f5779/packages/%40mantine/modals/src/ModalsProvider.tsx#L211

### If possible, include a link to a codesandbox with a minimal reproduction

https://codesandbox.io/p/sandbox/jolly-boyd-45rsvz

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment] 2024-01-17 12:23
https://github.com/mantinedev/mantine/assets/10353856/06370370-f3b2-4b41-930b-35b9c5a1c296

I cannot reproduce the issue on the provided codesandbox, there is no error in the console

**Comment by dimbslmh** [comment] 2024-01-17 14:39
> 2024-01-17.16.22.24.mov 
> I cannot reproduce the issue on the provided codesandbox, there is no error in the console

Please try again, I've changed the default trapFocus to false.

https://github.com/mantinedev/mantine/assets/745635/14ffe326-7e7e-4695-a42a-908994d99e23

**Comment by rtivital** [comment] 2024-01-17 19:20
Fixed in [7.4.2](https://github.com/mantinedev/mantine/releases/tag/7.4.2)

**Closed by rtivital** 2024-01-17 19:20 UTC
Labels: Fixed patch
