### ISSUE TITLE
Unexpected value 0.9375rem parsing height attribute. on PasswordInput with firefox

### ISSUE THREAD

**Issue by underthinks** [mantinedev/mantine#4420] opened 2023-06-18 20:11 UTC
### What package has an issue

@mantine/core

### Describe the bug

Getting the warning Unexpected value 0.9375rem parsing height/width attribute when using firefox for ubuntu (114.0.1). narrowed it down to to visibility toggle on the password input:

`<button class="mantine-UnstyledButton-root mantine-ActionIcon-root mantine-PasswordInput-visibilityToggle mantine-16c6coe" type="button" tabindex="-1" aria-hidden="true"><svg width="0.9375rem" height="0.9375rem" viewBox="0 0 15 15" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M7.5 11C4.80285 11 2.52952 9.62184 1.09622 7.50001C2.52952 5.37816 4.80285 4 7.5 4C10.1971 4 12.4705 5.37816 13.9038 7.50001C12.4705 9.62183 10.1971 11 7.5 11ZM7.5 3C4.30786 3 1.65639 4.70638 0.0760002 7.23501C-0.0253338 7.39715 -0.0253334 7.60288 0.0760014 7.76501C1.65639 10.2936 4.30786 12 7.5 12C10.6921 12 13.3436 10.2936 14.924 7.76501C15.0253 7.60288 15.0253 7.39715 14.924 7.23501C13.3436 4.70638 10.6921 3 7.5 3ZM7.5 9.5C8.60457 9.5 9.5 8.60457 9.5 7.5C9.5 6.39543 8.60457 5.5 7.5 5.5C6.39543 5.5 5.5 6.39543 5.5 7.5C5.5 8.60457 6.39543 9.5 7.5 9.5Z" fill="currentColor" fill-rule="evenodd" clip-rule="evenodd"></path></svg></button>`

### What version of @mantine/hooks page do you have in package.json?

"@mantine/core": "^6.0.13",

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

### Possible fix

Change to pixel value

**Comment by rtivital** [comment] 2023-06-19 05:28
Duplicate of #3699

**Closed by rtivital** 2023-06-19 05:28 UTC
