### ISSUE TITLE
Popover onClose isn't triggered on ESC or onClickOutside in controlled mode

### ISSUE THREAD

**Issue by Lenwyths** [mantinedev/mantine#7211] opened 2024-12-03 08:05 UTC
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.14.3

### What package has an issue?

@mantine/core

### What framework do you use?

create-react-app (CRA)

### In which browsers you can reproduce the issue?

Chrome

### Describe the bug

It seems the recent changes/fixes to the Popover onClose has changed it's behaviour slightly and it's no longer fired when I try to close the popover with ESC or by clicking outside in controlled mode.

See codesandbox for an example.

I didn't try the previous versions, but it was working fine for me in: [7.13.2](https://github.com/mantinedev/mantine/releases/tag/7.13.2)

### If possible, include a link to a codesandbox with a minimal reproduction

https://codesandbox.io/p/sandbox/6g7h3h

### Possible fix

Haven't checked the source code, but I'm guessing these were just forgotten when fixing bugs. So maybe just a dependancy in a hook or something.

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment] 2024-12-03 08:07
Duplicate of #7019
See the linked issue to learn more

**Closed by rtivital** 2024-12-03 08:07 UTC
