### ISSUE TITLE
DatePicker, clear button opens the popover

### ISSUE THREAD

**Issue by esistgut** [mantinedev/mantine#1846] opened 2022-07-24 23:11 UTC
### What package has an issue

@mantine/dates

### Describe the bug

Using the clear button on the DatePicker component opens the popover prompting the user to insert another date. Shouldn't the clear button just clear the input? Replacing the date can be done just fine without the clear button, right?

### In which browser did the problem occur

Firefox 102.0.1

**Comment by pmalliotas** [comment] 2022-07-30 15:25
Hi @esistgut! 

This is not a bug but rather the expected behaviour.
You can disable this by setting the openDropdownOnClear to false in the DatePicker component props

**Comment by rtivital** [comment] 2022-07-30 15:30
Yep, it makes more sense, I'll do that with next patch

**Comment by pmalliotas** [comment] 2022-07-30 15:31
I can change that and make a pull request

**Comment by rtivital** [comment] 2022-07-30 15:32
No, thanks, I'll do it on my side

**Comment by rtivital** [comment] 2022-08-05 17:48
Fixed in 5.0.3

**Closed by rtivital** 2022-08-05 17:48 UTC
Labels: bug
