### ISSUE TITLE
Support for Zod Async Refinement

### ISSUE THREAD

**Issue by jiyuu-jin** [mantinedev/mantine#1557] opened 2022-06-02 22:45 UTC
### What package has an issue

@mantine/form

### Describe the bug

I have a form where I'm trying to do an async lookup on a form value to see if it's valid.  I'm using the zodResolver and a Zod  async refinement,

[Zod Docs - Async Refinement](https://zod.dev/?id=asynchronous-refinements)

The following code throws `Unhandled Runtime Error
Error: Async refinement encountered during synchronous parse operation. Use .parseAsync instead.`

Zod Schema
```typescript
 const accountFormSchema = z.object({
    username: z.string()
      .min(3, { message: 'Username should have at least 3 letters' })
      .max(24, { message: 'Username should not be longer than 24 letters' }),
    displayName: z.string(),
    website: z.string(),
    description: z.string(),
    members: z.string().refine(async (id) => {
      await fetch("https://api.thedogapi.com/v1/images/search");
      return true;
    }),
    newMember: z.string(),
  });
  ```
  
 useForm 
 ```typescript
   const accountForm = useForm({
    schema: zodResolver(accountFormSchema),
    initialValues: {
      username: props.initialValues.username,
      displayName: props.initialValues.displayName,
      website: props.initialValues.website,
      description: props.initialValues.description,
      members: '',
      newMember: '',
    },
  });
 ```

### In which browser did the problem occur

Chrome/Brave

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

**Comment by rtivital** [comment] 2022-06-03 08:49
Duplicate of #1100

**Closed by rtivital** 2022-06-03 08:49 UTC
Labels: bug
