### ISSUE TITLE
Tabs in Modal opened from Menu cause tab to become unresponsive in Firefox

### ISSUE THREAD

**Issue by sienkiewiczkm** [mantinedev/mantine#6152] opened 2024-04-30 15:50 UTC
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.8.1

### What package has an issue?

@mantine/core

### What framework do you use?

Vite

### In which browsers you can reproduce the issue?

Firefox

### Describe the bug

In `<Menu/>` I have a option that opens the `<Modal/>`, which inside contains the `<Tabs/>`. For some reason on Firefox, if you click on "Tab 2" whole **browser tab** will freeze and you'll be forced to kill the tab, minimal component that is able to trigger the failure:

```tsx
const MyDemo = () => {
  const [opened, { open, close }] = useDisclosure(false);
  const modal = (
    <Modal opened={opened} onClose={close} title="hi" size="xl">
      <Tabs defaultValue="t1">
        <Tabs.List>
          <Tabs.Tab value="t1">Tab 1</Tabs.Tab>
          <Tabs.Tab value="t2">Tab 2</Tabs.Tab>
        </Tabs.List>
        <Tabs.Panel value="t1">Tab 1</Tabs.Panel>
        <Tabs.Panel value="t2">Tab 2</Tabs.Panel>
      </Tabs>
    </Modal>
  );

  return (
    <>
      <Text>Bug is reproducible only in Firefox</Text>
      <Menu shadow="md" width={350} position="bottom-end">
        <Menu.Target>
          <Button variant="subtle">Magic menu</Button>
        </Menu.Target>
        <Menu.Dropdown>
          <Menu.Label>Section</Menu.Label>
          <Menu.Item onClick={() => open()}>Open!</Menu.Item>
        </Menu.Dropdown>
      </Menu>
      {modal}
    </>
  );
};
```

User-agent: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:125.0) Gecko/20100101 Firefox/125.0`

This issue as far I can tell can be reproduced in Firefox and causes total freeze in the tab.

Demo:
- https://sienkiewiczkm.github.io/mantine-popovers-firefox-bug/ (repo: https://github.com/sienkiewiczkm/mantine-popovers-firefox-bug)
- also same thing in Codesandbox

I tried debugging this very deep into React internals, but I couldn't find a root cause.

Edit: Additional piece of context (possibly useless), strangely in my main repo (large app that I cannot share) this bug occurs only when I set `NODE_ENV` to `production`. That's not strictly required for the small repro repos.

### If possible, include a link to a codesandbox with a minimal reproduction

https://codesandbox.io/p/sandbox/mantine-combobox-in-scrollable-popovers-forked-6qkwyn

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by sienkiewiczkm** [comment] 2024-04-30 22:43
I just tested Firefox (125.0.3) on Windows and it works, so it appears that issue is MacOS exclusive (confirmed also on another MacOS machine). I don't know if Linux is affected.

**Comment by ndelon** [comment] 2024-08-06 15:41
FYI, I encountered the same problem under similar/same circumstances:
- Mantine 7.11.2
- Firefox 128.0.3
- Tabs in a modal

And as described in https://github.com/webcompat/web-bugs/issues/136574, if the modal is opened => closed => re-opened before switching tabs, then the freeze does NOT happen.

**Comment by ndelon** [comment] 2024-08-15 15:24
Good news: I no longer encounter this issue with the latest Firefox version (129.0.1).

**Comment by Kenzo-Wada** [comment] 2024-08-15 16:00
> I don't know if Linux is affected.

I've tested with Ubunutu, but it didnt appear so this issue may occur only for MacOS

**Comment by ndelon** [comment] 2024-09-27 16:56
> FYI, I encountered the same problem under similar/same circumstances:
> 
>     * Mantine 7.11.2
> 
>     * Firefox 128.0.3
> 
>     * Tabs in a modal
> 
> 
> And as described in [webcompat/web-bugs#136574](https://github.com/webcompat/web-bugs/issues/136574), if the modal is opened => closed => re-opened before switching tabs, then the freeze does NOT happen.

After some recent updates:
- Mantine 7.12.2
- Firefox 130.0.1
- macOS 14.6.1

I'm not able to reproduce this issue anymore.

**Comment by rtivital** [comment] 2024-10-03 09:44
I've checked, the issue seems to have been resolved in one of the previous releases, it works correctly if all Mantine packages are updated to 7.13.1

**Closed by rtivital** 2024-10-03 09:44 UTC
Labels: Fix Unknown
