### ISSUE TITLE
Autocomplete does not work on Firefox Mobile

### ISSUE THREAD

**Issue by jolebas** [mantinedev/mantine#2173] opened 2022-08-19 17:10 UTC
### What package has an issue

@mantine/core

### Describe the bug

On Firefox Mobile the SPACE key doesn't work in the Autocomplete, The first time you press nothing happens, the second time it deletes the text already typed.

### What version of @mantine/hooks page do you have in package.json?

5.2.0

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

**Comment by rtivital** [comment] 2022-08-19 18:02
Hi @jolebas, here is the list of browsers that we officially support – https://mantine.dev/pages/about/#browser-support
Firefox mobile has 0.3% of usage, so it does not make much sense to maintain it on our side. If you know how to fix the issue, then feel free to submit a PR. Otherwise, I doubt that it will be solved.

**Comment by AntoninHuaut** [comment] 2022-08-28 10:00
I can't reproduce the problem with Firefox Mobile, the Autocomplete component (or MultiSelect with autocomplete) seems to work perfectly.

**Comment by jolebas** [comment] 2022-08-28 10:27
> I can't reproduce the problem with Firefox Mobile, the Autocomplete component (or MultiSelect with autocomplete) seems to work perfectly

How bizarre. If I go right now in FF mobile on https://mantine.dev/core/autocomplete/ I can recreate

**Comment by rtivital** [comment] 2022-09-04 09:08
@jolebas I cannot reproduce the issue is well (iOS and Android 11 – Realme 11 Pro), closing this as it cannot be reproduced

https://user-images.githubusercontent.com/10353856/188306065-36b60a74-c7d6-4be8-be7c-fc269de4e5da.mp4

**Closed by rtivital** 2022-09-04 09:08 UTC
Labels: help wanted
