### ISSUE TITLE
Menu is not closed when clicking outside in Mobile

### ISSUE THREAD

**Issue by juan-manuel-alberro** [mantinedev/mantine#4855] opened 2023-09-24 12:43 UTC
### What package has an issue

@mantine/core

### Describe the bug

The `<Menu />` component is not closed when clicking outside in Mobile devices, I can recreate this using the Chrome simulator and a phisical mobile devices. Is only closed when you touch again in the `Target`.
Providing the `closeOnClickOutside` prop doesn't solve the problem.

https://github.com/mantinedev/mantine/assets/7114488/7c696510-35f7-4fae-879a-250ff73a5822

Thanks.

### What version of @mantine/* page do you have in package.json? (Note that all @mantine/* packages must have the same version in order to work correctly)

7.0.0

### If possible, please include a link to a codesandbox with the reproduced problem

https://mantine.dev/core/menu/#usage

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by rtivital** [comment] 2023-09-25 13:10
The issue is resolved in [7.0.1](https://github.com/mantinedev/mantine/releases/tag/7.0.1)

**Closed by rtivital** 2023-09-25 13:10 UTC
Labels: Completed patch
