### ISSUE TITLE
Controlled searchable select is broken

### ISSUE THREAD

**Issue by ramiel** [mantinedev/mantine#4948] opened 2023-10-02 10:21 UTC
### What package has an issue

@mantine/core

### Describe the bug

After an element has been selected in a controlled searchable select, it's not possible to use the keyboard to delete the content and search again.

https://github.com/mantinedev/mantine/assets/324687/dacd7de5-9d65-462f-a18c-047e6713f797

### What version of @mantine/* packages do you have in package.json? (Note that all @mantine/* packages must have the same version in order to work correctly)

7.1.0

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/loving-firefly-g4v92w?file=/src/SearchableSelect.tsx

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by rtivital** [comment] 2023-10-02 10:38
Duplicate of #4909

**Closed by rtivital** 2023-10-02 10:38 UTC
