### ISSUE TITLE
Hovering tree node in Tree component causes re-render

### ISSUE THREAD

**Issue by xauuu** [mantinedev/mantine#7309] opened 2024-12-27 06:36 UTC
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.15.2

### What package has an issue?

@mantine/core

### What framework do you use?

create-react-app (CRA)

### In which browsers you can reproduce the issue?

Chrome

### Describe the bug

When using `useTree()`, I hover mouse over tree node the whole component is re-rendered.
It works normally without adding tree props

### If possible, include a link to a codesandbox with a minimal reproduction

https://codesandbox.io/p/sandbox/mantine-react-template-forked-48thrd

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment] 2024-12-27 06:58
Duplicate of #7266

**Closed by rtivital** 2024-12-27 06:58 UTC

**Comment by xauuu** [comment] 2024-12-27 08:16
Is there a solution to this problem?
