### ISSUE TITLE
Massive layout shifts with next@12.1.6

### ISSUE THREAD

**Issue by Uniiq** [mantinedev/mantine#1690] opened 2022-06-27 09:24 UTC
### What package has an issue

@mantine/core

### Describe the bug

Hello, if found a bug with next@12.1.6 and mantine@4.2.2. Older mantine version have the same bug.

I updated my project to next@12.1.6 and had massive layout shifts when loading the page:

Here a example:
![Screencast from 2022-06-27 11_06_03](https://user-images.githubusercontent.com/30861773/175905673-6712682f-00c7-4381-a326-0f2647807154.gif)

After a downgrade to next@12.1.5 the bug was resolved.

How you can reproduce it:

1. clone https://github.com/mantinedev/mantine-next-template
2. Update to next@12.1.6
3. run `yarn build`
4. run `yarn start`
5. Open http://localhost:3000 and throttle your browser to slow 3G

### In which browser did the problem occur

Chrome Version 103.0.5060.53

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

**Comment by rtivital** [comment] 2022-06-27 13:33
Next.js 12.1.6 has issue with server side rendering, as far as I know, the issue will be resolved in 12.1.7. For now, you can downgrade to 12.1.5. The issue is not on Mantine side.

**Closed by rtivital** 2022-06-27 13:33 UTC
Labels: bug
