### ISSUE TITLE
Badges don't have their text centered when zooming in

### ISSUE THREAD

**Issue by nicolassanmar** [mantinedev/mantine#5484] opened 2023-12-28 15:44 UTC
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.3.2

### What package has an issue?

@mantine/core

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

Chrome

### Describe the bug

With a zoom of 110% in chrome (reproducible in other zoom levels as well) badge text is not centered (badge from https://mantine.dev/core/badge/ ):
![image](https://github.com/mantinedev/mantine/assets/57573579/669ee33f-105f-498d-9922-18ed4dd44c47)

You can see that the text has less padding on the top, than on the bottom.

I think this happens because the browser does not properly center the text over the assigned height of `line-height`.

I was only able to reproduce this on Chrome (I did not encounter this issue on Firefox), so it might be a bug on their side, but maybe we can do something about it anyway.

### If possible, include a link to a codesandbox with a minimal reproduction

https://mantine.dev/core/badge/

### Possible fix

Not entirely sure how to fix this properly.
I tried reducing the line height, but that does not always fix the issue (it usually works for preventing the issue when zooming in, but not on zoom out)

Maybe we need to wrap this up into another div to guarantee that the text is centered?

### Self-service

- [X] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment] 2024-01-03 09:38
https://github.com/mantinedev/mantine/assets/10353856/965ac0a6-59f7-4cfd-95dd-14ead33ee25c

I cannot reproduce the issue in Chrome

**Comment by nicolassanmar** [comment] 2024-01-03 12:58
Thanks for trying to reproduce it @rtivital!

Maybe it depends on the OS as well? I'm on Ubuntu linux, with chrome 120.0.6099.129

Here is my reproduction video:

https://github.com/mantinedev/mantine/assets/57573579/e1db0612-3c44-4c79-bfaa-698b48c370ea

**Comment by arkreddy21** [comment] 2024-01-12 03:25
@nicolassanmar 
Try installing segoe ui font. And other fonts too if you wish like helvetica, arial, roboto. 
This issue should be related to linux. It doesn't come with proprietary fonts like segoe ui which most websites use. So you'll encounter this issue in a lot of websites.

**Comment by nicolassanmar** [comment] 2024-01-12 13:03
@arkreddy21 
I don't think this is related to fonts.
I changed the `font-famliy` to different installed fonts, and the issue could be reproduced with all of them:
![image](https://github.com/mantinedev/mantine/assets/57573579/9ef49c79-1296-481d-aca7-d4a99a821fe1)



Furthermore, opening the site with Firefox changing the font-family there also reproduces this issue (it happens on zoom out) 
![image](https://github.com/mantinedev/mantine/assets/57573579/5fa0c254-41b7-4cd1-bba9-dbc49029c324)

**Comment by arkreddy21** [comment] 2024-01-12 14:20
I can't expain it properly, but do try installing the fonts once. I had this problem on many websites where text inside some containers are not centered properly. It all fixed once I installed segoe ui font, so worth a try. 
It already uses some default installed font even if you didn't override it. Those default fonts don't seem to work well within websites. But I'm sure this is not related to mantine.

**Comment by rtivital** [comment] 2024-01-27 15:54
The bug seems to be unique to some linux distro or fonts installed on the user OS. It is not planned to be fixed in the library.

**Closed by rtivital** 2024-01-27 15:54 UTC
Labels: Linux
