### ISSUE TITLE
Using the toggle method provided internally by useDisclosure can cause Menu to rely on rendering beyond the maximum update depth

### ISSUE THREAD

**Issue by xshuxin** [mantinedev/mantine#4029] opened 2023-04-07 16:07 UTC
### What package has an issue

@mantine/core

### Describe the bug

When Menu uses the toggle method provided internally by useClosure to control unfolding and collapsing, it can lead to dependency rendering exceeding the maximum update depth and falling into a dead loop. The following is the error message from the console: "Maximum update depth exceeded. This can happen when a component calls setState inside useEffect, but useEffect either does not have a dependency array, or one of the dependency changes on every render.

### What version of @mantine/hooks page do you have in package.json?

^6.0.5

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/fast-wave-lfz8d3?file=/src/App.tsx

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Possible fix

Through code retrieval, I found that Menu repeatedly called the "onClose" and "onOpen" methods internally. When "toggle" was executed, the "_opened" state became dependent, constantly triggering the closure and opening methods of Popover. "_opened" was constantly changing, leading to an infinite loop. At present, I have annotated the "onClose" and "onOpen" methods in "Popover", leaving only setOpened to control the unfolded and collapsed state. I have found that the dead loop problem has been resolved, and no new issues have been found. But I don't know if this solution will bring about other problems. Is there a better solution?

<img width="1408" alt="image" src="https://user-images.githubusercontent.com/105474651/230639719-d85a910f-645c-4aa4-b37e-4b9448bcdd66.png">

This is my PR:
https://github.com/mantinedev/mantine/pull/4030

**Comment by xshuxin** [comment] 2023-04-07 16:43
I'm very sorry, the word was written incorrectly. It should be 'useClosure' ->'useClosure'

**Comment by xshuxin** [comment] 2023-04-07 16:45
I'm very sorry, the word was written incorrectly. It should be 'useClosure' ->'use disclosure'

**Comment by cyantree** [comment] 2023-04-07 19:57
I think the issue is using `toggle()` which seems to trigger an endless loop. Try setting the state explicitly.
Here's an updated sandbox:
https://codesandbox.io/s/ecstatic-chihiro-3rvt8w

#3817 had a similar issue.

IMHO `onChange()` shouldn't be called when `opened` will be changed programatically as this violates data flow patterns involving UI interaction. It should be only called when the `Menu.target` gets clicked.
For `onOpen()` and `onClose()` that's already the case.

@rtivital Do you agree with this? Then I can prepare a PR for this change.

**Comment by xshuxin** [comment] 2023-04-08 00:45
> I think the issue is using `toggle()` which seems to trigger an endless loop. Try setting the state explicitly. Here's an updated sandbox: https://codesandbox.io/s/ecstatic-chihiro-3rvt8w
> 
> #3817 had a similar issue.
> 
> IMHO `onChange()` shouldn't be called when `opened` will be changed programatically as this violates data flow patterns involving UI interaction. It should be only called when the `Menu.target` gets clicked. For `onOpen()` and `onClose()` that's already the case.
> 
> @rtivital Do you agree with this? Then I can prepare a PR for this change.

**Comment by xshuxin** [comment] 2023-04-08 00:47
> > I think the issue is using `toggle()` which seems to trigger an endless loop. Try setting the state explicitly. Here's an updated sandbox: https://codesandbox.io/s/ecstatic-chihiro-3rvt8w
> > #3817 had a similar issue.
> > IMHO `onChange()` shouldn't be called when `opened` will be changed programatically as this violates data flow patterns involving UI interaction. It should be only called when the `Menu.target` gets clicked. For `onOpen()` and `onClose()` that's already the case.
> > @rtivital Do you agree with this? Then I can prepare a PR for this change.

**Comment by xshuxin** [comment] 2023-04-08 01:02
> I think the issue is using `toggle()` which seems to trigger an endless loop. Try setting the state explicitly. Here's an updated sandbox: https://codesandbox.io/s/ecstatic-chihiro-3rvt8w
> 
> #3817 had a similar issue.
> 
> IMHO `onChange()` shouldn't be called when `opened` will be changed programatically as this violates data flow patterns involving UI interaction. It should be only called when the `Menu.target` gets clicked. For `onOpen()` and `onClose()` that's already the case.
> 
> @rtivital Do you agree with this? Then I can prepare a PR for this change.

That's right! I also discovered yesterday that except for the 'toggle()' of 'useClosure', all other methods for controlling opening and closing can be used normally. But it seems that our two starting points are completely different. At that time, I found that the "setOpened" inside Menu completely covered all situations, including "onOpen()" and "onClose()" inside "Popover", which caused the "_opened" state to change repeatedly, leading to falling into an endless loop. Therefore, I removed the control method inside "Popover" and found that the problem was solved. Hahaha, it was my thinking that was too simplistic, I didn't consider the interaction process and learned from you~

**Comment by rtivital** [comment] 2023-04-08 04:36
> Do you agree with this?

Yes, I'm fine with this change

**Comment by rtivital** [comment] 2023-04-18 06:21
Fixed in 6.0.8

**Closed by rtivital** 2023-04-18 06:21 UTC
Labels: review required
