### ISSUE TITLE
Problem rendering text in Rich Text Editor when text are pasted from clipboard.

### ISSUE THREAD

**Issue by SAR-dev** [mantinedev/mantine#1703] opened 2022-06-30 07:23 UTC
### What package has an issue

@mantine/rte

### Describe the bug

When I copy some rich text from elsewhere and paste in editor somewhere randomly it doesn't work as expected. 
Video link : [https://nimb.ws/x156Fv](https://nimb.ws/x156Fv)
The problem occurs when I paste directly. But if I paste as plain text the problem doesn't occur.

### In which browser did the problem occur

Chrome

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/focused-tree-1pv7gz

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Possible fix

Add an explicit function to handle copy event.

**Comment by ercgrat** [comment] 2022-08-04 00:58
What's the intended behavior @SAR-dev? What's happening kind of makes sense to me. The formatting of the copied text is getting applied to everything on the same line. You can reproduce it on the Quill home page.

https://quilljs.com/

**Comment by rtivital** [comment] 2022-08-05 17:50
Seems like it is a default quill.js behavior, closing the issue

**Closed by rtivital** 2022-08-05 17:50 UTC
Labels: help wanted, bug, rte
