### ISSUE TITLE
[Mantine 7.14.3 / NextJS 15.0.4 / React 19.0] Menu.Target typescript error

### ISSUE THREAD

**Issue by bobbysciacchitano** [mantinedev/mantine#7227] opened 2024-12-06 11:59 UTC
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.14.3

### What package has an issue?

@mantine/core

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

Not applicable – issue is not related to the browser

### Describe the bug

I'm currently building a menu component and came across this exception why trying to build (TS):

```
Type error: 'Menu.Target' cannot be used as a JSX component.
  Its type 'ForwardRefExoticComponent<MenuTargetProps & RefAttributes<HTMLElement>>' is not a valid JSX element type.
    Type 'ForwardRefExoticComponent<MenuTargetProps & RefAttributes<HTMLElement>>' is not assignable to type '(props: any) => ReactNode'.
      Type 'import("/Users/bobby/Documents/Development/embark/node_modules/@mantine/core/node_modules/@types/react/index").ReactNode' is not assignable to type 'React.ReactNode'.
        Type 'ReactElement<any, string | JSXElementConstructor<any>>' is not assignable to type 'ReactNode'.
          Property 'children' is missing in type 'ReactElement<any, string | JSXElementConstructor<any>>' but required in type 'ReactPortal'.
```

This is my example implementation which I could reproduce the issue:

```
import { Button, Menu } from "@mantine/core";

type EntrySettingsProps = {
  form: Partial<SessionEntry | ProgramEntry>;
  onChange: OnFormChange;
  validation: ValidationErrors;
};

export function EntrySettings({}: EntrySettingsProps) {
  return (
    <Menu>
      <Menu.Target>
        <Button>Toggle menu</Button>
      </Menu.Target>
      <Menu.Dropdown>
        <Menu.Item>Testing</Menu.Item>
      </Menu.Dropdown>
    </Menu>
  );
}
```

package.json file:

```
  "dependencies": {
    "@mantine/core": "^7.14.3",
    "@mantine/hooks": "^7.14.3",
    "date-fns": "^4.1.0",
    "next": "15.0.4",
    "react": "19.0.0",
    "react-dom": "19.0.0"
  },
  "devDependencies": {
    "@types/node": "^20",
    "@types/react": "^19",
    "@types/react-dom": "^19",
    "eslint": "^8",
    "eslint-config-next": "15.0.4",
    "postcss": "^8.4.49",
    "postcss-preset-mantine": "^1.17.0",
    "postcss-simple-vars": "^7.0.1",
    "prettier": "^3.3.3",
    "typescript": "^5"
  }
```

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment] 2024-12-06 12:18
https://mantine.dev/guides/next/#compound-components-in-server-components

**Comment by kenzaflow** [comment] 2024-12-06 12:43
This is also happening in Vite (SPA), even with MenuTarget (no Menu.Target)

Only in that component

![image](https://github.com/user-attachments/assets/ef04578d-5840-48ca-ac6f-dd9b9ce0c7fd)

```tsx
'MenuTarget' cannot be used as a JSX component.
  Its type 'ForwardRefExoticComponent<MenuTargetProps & RefAttributes<HTMLElement>>' is not a valid JSX element type.
    Type 'ForwardRefExoticComponent<MenuTargetProps & RefAttributes<HTMLElement>>' is not assignable to type '(props: any) => ReactNode'.
      Type 'import("c:/Users/kevinzaracho/Desktop/poxs/poxs-v3-old/poxs-client/node_modules/@mantine/core/node_modules/@types/react/index").ReactNode' is not assignable to type 'React.ReactNode'.
        Type 'ReactElement<any, string | JSXElementConstructor<any>>' is not assignable to type 'ReactNode'.
          Property 'children' is missing in type 'ReactElement<any, string | JSXElementConstructor<any>>' but required in type 'ReactPortal'.ts(2786)
```

**Comment by kenzaflow** [comment] 2024-12-06 12:44
After update to React 19:

This is also happening in Vite (SPA), even with MenuTarget (no Menu.Target)

Only in that component

![image](https://github.com/user-attachments/assets/ef04578d-5840-48ca-ac6f-dd9b9ce0c7fd)

```tsx
'MenuTarget' cannot be used as a JSX component.
  Its type 'ForwardRefExoticComponent<MenuTargetProps & RefAttributes<HTMLElement>>' is not a valid JSX element type.
    Type 'ForwardRefExoticComponent<MenuTargetProps & RefAttributes<HTMLElement>>' is not assignable to type '(props: any) => ReactNode'.
      Type 'import(".../node_modules/@mantine/core/node_modules/@types/react/index").ReactNode' is not assignable to type 'React.ReactNode'.
        Type 'ReactElement<any, string | JSXElementConstructor<any>>' is not assignable to type 'ReactNode'.
          Property 'children' is missing in type 'ReactElement<any, string | JSXElementConstructor<any>>' but required in type 'ReactPortal'.ts(2786)
```

**Comment by bobbysciacchitano** [comment] 2024-12-06 13:17
Having reviewed the documentation, adding "use client" to the start of the module still causes an exception for me.

<img width="1002" alt="Screenshot 2024-12-07 at 12 14 58 AM" src="https://github.com/user-attachments/assets/a061d7b7-b9a8-4229-869d-bfa10b793767">

<img width="998" alt="Screenshot 2024-12-07 at 12 15 13 AM" src="https://github.com/user-attachments/assets/f938de57-532a-4e64-ad6d-875a4d9026aa">

**Comment by rtivital** [comment] 2024-12-06 14:02
Okay, this is a ts issue, probably with `@types/react`. Can you reproduce it in codesandbox?

**Comment by kenzaflow** [comment] 2024-12-06 16:45
I just tried with vite-min-template and nothing, I'm going to try with the one with eslint

**Comment by rtivital** [comment] 2024-12-08 08:27
Try adding resolutions to your package.json and reinstall dependencies:

```json
"resolutions": {
  "@types/react": "19.0.1",
  "@types/react-dom": "19.0.1"
}
```

**Comment by dincerpece** [comment] 2024-12-10 01:54
I installed only nextjs and mantine. I encountered the same problem in codesandbox.io. Then I installed it with yarn and built it and it worked without any problems.

yarn before:
![before](https://github.com/user-attachments/assets/d2169a6a-98f9-45dd-9e52-bf883e8554bc)


yarn after:
![after](https://github.com/user-attachments/assets/5485469a-53be-48ac-b6b6-dffe1c4bd6ef)

https://codesandbox.io/p/github/dincerpece/mantine-react19-test/draft/distracted-feistel?workspaceId=ws_JmivbuKahEgQ2p1ZSV2BLi

**Comment by dincerpece** [comment] 2024-12-10 02:10
Similarly, there was a problem locally before Yarn, but after the installation with Yarn, the problem disappeared. I hope it will be fixed without the need for an installation with Yarn.

local yarn before:
![before yarn](https://github.com/user-attachments/assets/bb312064-e3a9-484f-8a66-14dc43b2a588)

local yarn after:
![after yarn](https://github.com/user-attachments/assets/e991e8f5-5dba-41ee-a95f-03b61b9e4eac)

**Comment by bobbysciacchitano** [comment] 2024-12-10 03:37
Setting the resolutions to the suggested versions in yarn resolved my issue.

**Comment by felix-fuin** [comment] 2024-12-10 09:38
> ```json
> "resolutions": {
>   "@types/react": "19.0.1",
>   "@types/react-dom": "19.0.1"
> }
> ```

This solution works. (it should match versions installed)
And for those working with npm:

`"overrides": {
  "@types/react": "19.0.1",
  "@types/react-dom": "19.0.1"
}`

**Comment by rtivital** [comment] 2024-12-10 09:43
The issue is not related to Mantine. If you see this message, it means that there are two conflicting versions of `@types/react` are installed. To fix it:

- With yarn and probably with pnpm
```json
"resolutions": {
  "@types/react": "19.0.1",
  "@types/react-dom": "19.0.1"
}
```

- WIth npm:
```json
"overrides": {
  "@types/react": "19.0.1",
  "@types/react-dom": "19.0.1"
}
```

**Closed by rtivital** 2024-12-10 09:43 UTC
