### ISSUE TITLE
Mantine v7: highlight.js is huge

### ISSUE THREAD

**Issue by sparanoid** [mantinedev/mantine#5021] opened 2023-10-11 15:10 UTC
### What package has an issue

@mantine/code-highlight

### Describe the bug

v6:

<img width="473" alt="image" src="https://github.com/mantinedev/mantine/assets/96356/3aa4ee35-6bfd-4603-bfd5-6ddb5d078857">

v7:

<img width="473" alt="image" src="https://github.com/mantinedev/mantine/assets/96356/bc1f6ecf-7ca8-4a50-9a87-dc550920cffe">

After some investigations with next-bundle-analyzer:

<img width="705" alt="image" src="https://github.com/mantinedev/mantine/assets/96356/7ffad55c-ecd2-44b8-9892-eb917c30ce2e">

### What version of @mantine/* packages do you have in package.json? (Note that all @mantine/* packages must have the same version in order to work correctly)

7.1.2

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

### Possible fix

According to [highlight.js's documentation](https://highlightjs.org/#usage):

```js
// Using ES6 import syntax
import hljs from 'highlight.js/lib/core';
import javascript from 'highlight.js/lib/languages/javascript';

// Then register the languages you need
hljs.registerLanguage('javascript', javascript);
```

I think we could only import the syntax language I need to reduce the bundle size.

**Comment by rtivital** [comment] 2023-10-11 18:21
Duplicate of #4879

**Closed by rtivital** 2023-10-11 18:21 UTC
