### ISSUE TITLE
Issue with focusRingStyles and MultiSelect component

### ISSUE THREAD

**Issue by alimehasin** [mantinedev/mantine#3309] opened 2023-01-07 05:15 UTC
### What package has an issue

@mantine/core

### Describe the bug

It seems that `MultiSelect` gets wrong `focusRing` while other inputs have no problem

### What version of @mantine/hooks page do you have in package.json?

v5.10.0

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/xenodochial-waterfall-iuxjgd

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by Sajarin-M** [comment] 2023-01-11 05:37
Hi @alimehasin 🖐,

I am also experiencing this issue.

It appears that the source of the issue is

```js
style={{ overflow: 'hidden' }}
````

on line 637 of MultiSelect.tsx. I was thinking, why this is needed and whether removing it would cause any other issues? 🤔

**Comment by rtivital** [comment] 2023-09-19 06:54
This issue is closed for one of these reasons:

- It was fixed in 7.0
- It is no longer reproducible in 7.0
- It is no longer applicable in 7.0
- It does not have a reproduction

If you think that this issue was closed by mistake and it is still an issue in version 7.0, please reopen it.

**Closed by rtivital** 2023-09-19 06:54 UTC
Labels: Fixed in 7.0
