### ISSUE TITLE
Multiselect: creating new item by enter

### ISSUE THREAD

**Issue by zfarhad** [mantinedev/mantine#4351] opened 2023-06-02 14:03 UTC
### What package has an issue

@mantine/core

### Describe the bug

While we use 'MultiSelect' component and have the 'creatable' prop set to true, We should be able to create new item by pressing the enter key. I think this is a default behavior in all multi-select components and a lot of people would be pleasure if this feature were added.
I suggest to add a new optional prop 'createByEnter' that effect the behavior of the component. If this prop is not set to true, the default behavior of the component will not change.
If you agree, I can create a pull request with all necessary changes about this feature.

### What version of @mantine/hooks page do you have in package.json?

6.0.13

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

**Comment by noahsb** [comment] 2023-06-02 15:22
This functionality exists but was broken in a recent release. I filed a bug here: https://github.com/mantinedev/mantine/issues/4335

The relevant prop is `hoverOnSearchChange`

**Comment by rtivital** [comment] 2023-06-02 15:39
Duplicate of #4335

**Closed by rtivital** 2023-06-02 15:39 UTC

**Comment by zfarhad** [comment] 2023-06-04 08:51
I have looked at this #4335
The 'hoverOnSearchChange' prop is a useful feature but it's not exactly what I explained here. If we don't use the 'getCreateLabel' prop then we don't have a extra item in the selection list to call our creation function, So the 'hoverOnSearchChange' will not be useful in this case.
My requested prop to add (createByEnter) works only by pressing enter and does not require additional item in the list. This feature will make item creation extremely simple and necessary change in the component code is not too much.

**Comment by xiaohanyu** [comment] 2023-06-15 14:58
@zfarhad It seems that there's a breaking change from v4 to v5 which removes the "Enter to create new item" behavior: https://github.com/mantinedev/mantine/issues/2167.

@rtivital said the there're [plan](https://github.com/mantinedev/mantine/issues/2167#issuecomment-1412164972) to revamp this.

BTW, I also miss the feature of "Enter to create new item" here.
