### ISSUE TITLE
DateInput editing after selection

### ISSUE THREAD

**Issue by the-harry-higgins** [mantinedev/mantine#4741] opened 2023-09-08 16:16 UTC
### What package has an issue

@mantine/core

### Describe the bug

If you select a date using the calendar popover part of the DateInput component the date gets selected and formatted, the calendar popover closes, and your cursor is still in the input part of the DateInput. At this point, let's say you picked the wrong date, you press backspace/delete to edit the field. On every key press the date that you are editing gets reformatted and you are unable to edit the date correctly.

Backspace/delete works as expected while the popover is opened.

I believe that when you select a date using the calendar, the input should lose focus so that you are required to click into the input again to make changes. This will re-open the calendar popover and you are able to make edits without your input being reformatted on every change.

Problem area in lines 231-233 in DateInput.tsx:
```
useDidUpdate(() => {
    value !== undefined && !dropdownOpened && setInputValue(formatValue(value));
  }, [value]);
```

Example of behavior:

https://github.com/mantinedev/mantine/assets/14190311/beeb62e8-506f-48e1-a06c-ecaa0e805178

### What version of @mantine/hooks page do you have in package.json?

6.0.20

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

### Possible fix

I believe that when you select a date using the calendar, the input should lose focus so that you are required to click into the input again to make changes. This will re-open the calendar popover and you are able to make edits without your input being reformatted on every change.

**Comment by rtivital** [comment] 2023-09-21 19:04
Duplicate of https://github.com/mantinedev/mantine/issues/3818

**Closed by rtivital** 2023-09-21 19:04 UTC
