### ISSUE TITLE
Erroneous behavior SegmentedControl

### ISSUE THREAD

**Issue by Kudienko** [mantinedev/mantine#6637] opened 2024-08-05 21:17 UTC
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.10.2

### What package has an issue?

@mantine/core

### What framework do you use?

Other, I will specify in the bug description

### In which browsers you can reproduce the issue?

All

### Describe the bug

Custom build on react. When using SegmentedControl together with Accordion, an error occurs. When selecting a value in SegmentedControl and closing Accordion and reopening, the value of SegmentedControl does not save the selected value, but takes the value at which SegmentedControl was initialized in this case, "react".

### If possible, include a link to a codesandbox with a minimal reproduction

https://codesandbox.io/p/sandbox/mantine-react-template-forked-qjkr3s?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clzhghw600006356eol9hkemw%2522%252C%2522sizes%2522%253A%255B100%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clzhghw600002356ecvivvy59%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clzhghw600003356esl0ujws7%2522%257D%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clzhghw600005356efxj9hzk3%2522%257D%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clzhghw600002356ecvivvy59%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clzhghw5z0001356e9552o022%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clzhgkm620019356eiuz47nvf%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A1%252C%2522startColumn%2522%253A1%252C%2522endLineNumber%2522%253A21%252C%2522endColumn%2522%253A2%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clzhghw600002356ecvivvy59%2522%252C%2522activeTabId%2522%253A%2522clzhgkm620019356eiuz47nvf%2522%257D%252C%2522clzhghw600005356efxj9hzk3%2522%253A%257B%2522id%2522%253A%2522clzhghw600005356efxj9hzk3%2522%252C%2522activeTabId%2522%253A%2522clzhh2h9a000s356ddo8akiae%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clzhghw600004356ep60kaeu5%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%257D%252C%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522id%2522%253A%2522clzhh2h9a000s356ddo8akiae%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%252C%2522clzhghw600003356esl0ujws7%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clzhghw600003356esl0ujws7%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by ayovev** [comment] 2024-08-06 03:23
This sounds like a duplicate of [issue 6527](https://github.com/mantinedev/mantine/issues/6527)

**Comment by Kudienko** [comment] 2024-08-06 05:33
Yes, it looks similar. Can you tell me when the patch will be released with this solution to this problem?

**Closed** 2024-08-06 05:55 UTC
