### ISSUE TITLE
[Modal] Header zIndex not not enough when inner has formField

### ISSUE THREAD

**Issue by vaynevayne** [mantinedev/mantine#3797] opened 2023-03-16 03:38 UTC
### What package has an issue

@mantine/core

### Describe the bug

<img width="548" alt="image" src="https://user-images.githubusercontent.com/124666577/225507900-146be48b-03c0-4832-92b4-b558ba1ed0e4.png">

```jsx
 <Modal opened={opened} onClose={close} title="Header is sticky">
        <form>
        
          <SimpleGrid cols={1} mb="md">
        
            <DatePickerInput
              placeholder="Pick date"
        
              withAsterisk
              hideOutsideDates
              valueFormat="YYYY-MM-DD"
            />
            <DatePickerInput
              placeholder="Pick date"
            
              withAsterisk
              hideOutsideDates
              valueFormat="YYYY-MM-DD"
            />
            <DatePickerInput
              placeholder="Pick date"
           
              withAsterisk
              hideOutsideDates
              valueFormat="YYYY-MM-DD"
            />
            <DatePickerInput
              placeholder="Pick date"
         
              withAsterisk
              hideOutsideDates
              valueFormat="YYYY-MM-DD"
            />
            <DatePickerInput
              placeholder="Pick date"
         
              withAsterisk
              hideOutsideDates
              valueFormat="YYYY-MM-DD"
            />
            <DatePickerInput
              placeholder="Pick date"
              label="花费时间"
              withAsterisk
              hideOutsideDates
              valueFormat="YYYY-MM-DD"
            />
            <DatePickerInput
              placeholder="Pick date"
              label="花费时间"
              withAsterisk
              hideOutsideDates
              valueFormat="YYYY-MM-DD"
            />
          </SimpleGrid>

          <Group position="right" mt="md">
            <Button type="submit">确定</Button>
          </Group>
        </form>
      </Modal>
```

### What version of @mantine/hooks page do you have in package.json?

6.0.2

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/lucid-lena-zuuxx6?file=/src/Demo.tsx

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by rtivital** [comment] 2023-03-16 04:56
Duplicate of #3761

**Closed by rtivital** 2023-03-16 04:56 UTC
Labels: review required
