### ISSUE TITLE
Radio and SegmentedControl don't use radiogroup

### ISSUE THREAD

**Issue by arperry** [mantinedev/mantine#3706] opened 2023-03-07 16:04 UTC
### What package has an issue

@mantine/core

### Describe the bug

W3 spec for radio: https://www.w3.org/WAI/ARIA/apg/patterns/radio/

The Mantine radio components (Radio and SegmentedControl) do not conform to these standards:

* The radio buttons are contained in or owned by an element with role [radiogroup](https://w3c.github.io/aria/#radiogroup).
* The radiogroup element has a visible label referenced by [aria-labelledby](https://w3c.github.io/aria/#aria-labelledby) or has a label specified with [aria-label](https://w3c.github.io/aria/#aria-label).
* If elements providing additional information about either the radio group or each radio button are present, those elements are referenced by the radiogroup element or radio elements with the [aria-describedby](https://w3c.github.io/aria/#aria-describedby) property.

### What version of @mantine/hooks page do you have in package.json?

5.8.0

### If possible, please include a link to a codesandbox with the reproduced problem

Visible on every instance of the components

### Do you know how to fix the issue

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Possible fix

* Add a `label` property to SegmentedControl, similar to the property supported by Radio.
* Add `role="radiogroup"` to mantine-SegmentedControl-root (for SegmentedControl) and mantine-Group-root (for Radio).
* Add `aria-labelledby` to the radiogroup, linking it to the label.

I can attempt this change if desired, but this strikes me as a somewhat easy change for someone familiar with modifying Mantine code relative to the effort required to familiarize myself with the process.

**Comment by rtivital** [comment] 2023-09-25 13:12
The issue is resolved in [7.0.1](https://github.com/mantinedev/mantine/releases/tag/7.0.1)

**Closed by rtivital** 2023-09-25 13:12 UTC
Labels: Completed patch
