### ISSUE TITLE
component=Link breaking typed routes for dynamic route on Next 13

### ISSUE THREAD

**Issue by samiam376** [mantinedev/mantine#4854] opened 2023-09-24 00:48 UTC
### What package has an issue

@mantine/core

### Describe the bug

I have a Button that I'd like to make a Next Link to a dynamic route. 

The following Link component compiles correctly, 

```                  <Link
                    href={`/coi/dashboard/project-vendor/${data.projectVendor.id}/coverage/new`}
                  >
                    Upload Certificate
                  </Link>,
```

However, the following button triggers a build error 

```
                  <Button
                    key="update"
                    variant="subtle"
                    size="xs"
                    component={Link}
                    href={`/coi/dashboard/project-vendor/${data.projectVendor.id}/coverage/new`}
                  >
                    Upload Certificate
                  </Button>,
```

The build error is as follows 

``` 
Type error: Type '`/coi/dashboard/project-vendor/${string}/coverage/new`' is not assignable to type 'UrlObject | 
RouteImpl<unknown>'.

  240 |                     size="xs"
  241 |                     component={Link}
 242 |                     href={`/coi/dashboard/project-vendor/${data.projectVendor.id}/coverage/new`}
      |                     ^
  243 |                   >
  244 |                     Upload Certificate
  245 |                   </Button>,
```

### What version of @mantine/* page do you have in package.json? (Note that all @mantine/* packages must have the same version in order to work correctly)

^7.0.0

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by rtivital** [comment] 2023-09-28 10:19
The issue is fixed in 7.1.0, you can follow this guide to use polymorphic components with typed Next.js link – https://mantine.dev/guides/polymorphic/#polymorphic-components-with-generic-components

**Closed by rtivital** 2023-09-28 10:19 UTC
Labels: Completed minor
