### ISSUE TITLE
npm installs dependencies that have incompatible versions (FOUC Next.js, Remix)

### ISSUE THREAD

**Issue by codart1** [mantinedev/mantine#1390] opened 2022-05-05 09:37 UTC
### What package has an issue

@mantine/core

### Describe the bug

I just follow the official guide to integrating Remix with Mantine and see this flash of unstyled content issue:

https://user-images.githubusercontent.com/1023519/166897801-c658f2cf-1184-42c4-80d5-866bd52ebe9e.mp4

 

### In which browser did the problem occur

Chrome

### If possible, please include a link to a codesandbox with the reproduced problem

https://github.com/codart1/mantine-remix-fouc

**Comment by codart1** [comment] 2022-05-05 12:16
@rtivital Thanks, but how can a package manager be the root cause of this issue?

**Comment by rtivital** [comment] 2022-05-05 12:31
I do not know, it is just how npm started resolving dependencies recently, no idea how to fix it

**Comment by agergo** [comment] 2022-05-11 11:06
Could the issue be somehow related to the regression in Next.js 12.1.6: https://github.com/vercel/next.js/issues/36675 ? The FOUC disappeared for me after downgrading to 12.1.5 (I'm using `pnpm` btw)

**Comment by rtivital** [comment] 2022-05-11 12:23
Next.js issue – https://github.com/vercel/next.js/issues/36675

**Comment by rtivital** [comment] 2022-05-18 15:03
@thisisandreww do you use npm or pnpm?

**Comment by thisisandreww** [comment] 2022-05-18 16:57
I’m using npm

**Comment by codart1** [comment] 2022-05-19 03:27
NextJS issue? But I'm using Remix.

**Comment by tombohub** [comment] 2022-06-11 03:29
I am using yarn with Nextjs 12.1.6 and having FOUC.

The FOUC doesn't appear for MUI and Chakra.

**Comment by debel27** [comment] 2022-07-08 22:30
Isn't the FOUC caused by the injection of `<style>` elements at runtime ? 
Consider the following render sequence

- the app gets server-side rendered. The rendered HTML doesn't contain `<style>` tags
- the browser displays the (unstyled) app
- the app gets hydrated by client-side code. Mantine components' effects run and inject `<style>` tags
- styles get updated on screen, causing the FOUC to happen

@rtivital can you validate this ?
If so, is there a pre-compiled CSS stylesheet we can use to prevent FOUC from happening ?

Unfortunately, using the (undocumented :no_mouth:) `injectStylesIntoStaticMarkup` function server-side doesn't cut it for folks like me who stream the HTML as it gets rendered.

**Comment by rtivital** [comment] 2022-07-25 10:33
Should be fixed in 5.0, `@emotion/react` and `@emotion/server` packages are now required to be installed as peer dependencies

**Closed by rtivital** 2022-07-25 10:33 UTC
Labels: help wanted, bug
