### ISSUE TITLE
Height of SegmentedControl Label

### ISSUE THREAD

**Issue by FenderStrat85** [mantinedev/mantine#5738] opened 2024-02-07 15:20 UTC
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.1.3 in the app we're building and 7.5.1 in the codesandbox

### What package has an issue?

@mantine/core

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

All

### Describe the bug

Create a modal that contains a segmented control and is closed by default. On opening the modal, the segmented control label will be misaligned, but as soon as you click on any other items it will reset and work perfectly. 

I have recreated the issue in a codesandbox below.

This bug was also mentioned here:
https://github.com/mantinedev/mantine/issues/2994

On Modal opening
<img width="450" alt="Screenshot 2024-02-07 at 15 20 01" src="https://github.com/mantinedev/mantine/assets/77243567/d7da3668-cb25-4972-b9b0-63ba42d67eb9">

After selecting different item in segmented control
<img width="433" alt="Screenshot 2024-02-07 at 15 20 36" src="https://github.com/mantinedev/mantine/assets/77243567/6a7a814f-f37f-4c0a-9883-d120a05bf608">

### If possible, include a link to a codesandbox with a minimal reproduction

https://codesandbox.io/p/devbox/yt3v72?file=%2Fsrc%2FApp.jsx%3A2%2C29

### Possible fix

I have tried using setTimeouts to see if that resolves it which it doesn't

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment] 2024-02-07 16:40
Duplicate of #3330

**Closed by rtivital** 2024-02-07 16:40 UTC
