### ISSUE TITLE
[@mantine/charts] AreaChart not displaying data with Next.js 15

### ISSUE THREAD

**Issue by eugeniudedin** [mantinedev/mantine#7220] opened 2024-12-04 16:32 UTC
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.14.3

### What package has an issue?

@mantine/charts

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

All

### Describe the bug

`AreaChart` not displaying data. If change it to `LineChart` with same structure and same data, is working perfectly.

NextJS: 15.0.3
Mantine: 7.14.3
Recharts: 2.14.1

### If possible, include a link to a codesandbox with a minimal reproduction

https://codesandbox.io/p/devbox/mantine-area-chart-issue-y63fj6

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment] 2024-12-04 18:26
Provide a sandbox with a minimal reproduction.

**Comment by eugeniudedin** [comment] 2024-12-05 02:40
Reproduction

https://codesandbox.io/p/devbox/mantine-area-chart-issue-y63fj6

**Comment by TheNaubit** [comment] 2024-12-06 00:19
> Reproduction
> 
> https://codesandbox.io/p/devbox/mantine-area-chart-issue-y63fj6

I am also experiencing this issue and I am trying to find what could be the cause. And after downgrading the Next.js version in that minimal reproduction to Next.js 14.2.20, the AreaChart works so seems related to Next.js 15: https://codesandbox.io/p/devbox/mantine-area-chart-issue-y63fj6

**Comment by TheNaubit** [comment] 2024-12-06 00:57
Ok, I got my AreaChart working in Next.js 15 with React 19. I found this answer in the `recharts` GitHub repo, answering someone that had a similar issue as us: https://github.com/recharts/recharts/issues/4558#issuecomment-2135308117

Basically, `recharts` seems to not be working 100% fine with React 19 yet, and one dependency of it (`react-is`) is not updated in Recharts to support React 19.

So they suggested overriding the `react-is` lib to an alpha version with support to React 19. But I just checked, and the upgraded version is available: https://www.npmjs.com/package/react-is

Also, the Recharts people are going to release an upgraded version soon: https://github.com/recharts/recharts/issues/4558#issuecomment-2521569566

So, this is just a matter of waiting a couple of hours/days and then update `recharts` in the `@mantine/charts` package.

But if someone can not wait, I made it work by adding in my `package.json` an override:
```json
"overrides": {
		"react-is": "^19.0.0"
},
```
or if you are using pnpm:
```json
"pnpm": {
	"overrides": {
		"react-is": "^19.0.0"
	}
}
```

**Comment by ckifer** [comment] 2024-12-06 01:17
recharts maintainer here. This isn't just recharts. In react 19 `react-is` versions must match `react` and `react-dom` versions exactly in order for the matchers to _ever_ return true. This is the reason overrides must be used (and may still need to be used after the next release). If your lockfile is using React 19, but react-is is still on 16.8 or something else old then they will not work correctly.

Hopefully peerDeps and bringing your own `react-is` version will solve it but tbd until we try it out.

Now in 3.x we plan to remove react-is entirely so problem solved, but until then there has potential be some issues

**Comment by rtivital** [comment] 2024-12-12 08:25
Okay, this issue is not related to Mantine and does cannot be fixed on the library side, follow the instructions above to install the specific `react-is` version. For yarn, use `resolutions` field instead of `overrides`.

**Closed by rtivital** 2024-12-12 08:25 UTC

**Comment by rougsig** [comment] 2025-05-16 14:56
Can we add that link with warning notice into docs? https://mantine.dev/charts/area-chart/#usage
