### ISSUE TITLE
Error on useResizeObserver and Group

### ISSUE THREAD

**Issue by israelins85** [mantinedev/mantine#5780] opened 2024-02-16 17:48 UTC
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.5.3

### What package has an issue?

@mantine/core

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

None

### Describe the bug

Type 'MutableRefObject<HTMLDivElement | undefined>' is not assignable to type 'Ref<HTMLDivElement> | undefined'.
  Type 'MutableRefObject<HTMLDivElement | undefined>' is not assignable to type 'RefObject<HTMLDivElement>'.
    Types of property 'current' are incompatible.
      Type 'HTMLDivElement | undefined' is not assignable to type 'HTMLDivElement | null'.
        Type 'undefined' is not assignable to type 'HTMLDivElement | null'.typescript(2322)

### If possible, include a link to a codesandbox with a minimal reproduction

https://codesandbox.io/p/sandbox/mantine-group-ref-error-kvx58y

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by israelins85** [comment] 2024-02-16 17:49
Is wrong use only: const [refRightSection, rectRightSection] =
    useResizeObserver<HTMLDivElement>();

**Comment by pauledwards241** [comment] 2024-02-21 11:27
I'm having a similar issue, looks to be caused by the fix to https://github.com/mantinedev/mantine/issues/5752

**Comment by rtivital** [comment] 2024-02-27 07:14
Fixed in [7.6.1](https://github.com/mantinedev/mantine/releases/tag/7.6.1)

**Closed by rtivital** 2024-02-27 07:14 UTC
Labels: Fixed patch

**Comment by tobeycodes** [comment] 2024-02-27 19:07
@rtivital I'm a little confused by this fix. Why are we now returning any?

```
error  Unsafe array destructuring of a tuple element with an `any` value  @typescript-eslint/no-unsafe-assignment
ui:lint:   
error  Unsafe member access .current on an `any` value                    @typescript-eslint/no-unsafe-member-access
```

**Comment by kenzaflow** [comment] 2024-03-04 16:31
Same here: https://github.com/mantinedev/mantine/commit/ec4fcf77d83a63ef050547e82d69bd3a03e1ef34#commitcomment-139346444

```
Unsafe assignment of an `any` value.eslint[@typescript-eslint/no-unsafe-assignment](https://typescript-eslint.io/rules/no-unsafe-assignment)
```
