### ISSUE TITLE
TypeError: Cannot use 'in' operator to search for 'xs' in undefined

### ISSUE THREAD

**Issue by rishabh-te** [mantinedev/mantine#6900] opened 2024-09-27 08:48 UTC
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

 @mantine/carousel. 7.13.0

### What package has an issue?

@mantine/carousel

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

Chrome

### Describe the bug

I tried using  @mantine/carousel

⨯ ../src/core/utils/get-breakpoint-value/get-breakpoint-value.ts (4:7) @ breakpoint
 ⨯ TypeError: Cannot use 'in' operator to search for 'xs' in undefined
    at Array.map (<anonymous>)
digest: "418810984"
  2 | import { px } from '../units-converters';
  3 |
> 4 | export function getBreakpointValue(breakpoint: number | string, theme: MantineTheme) {
    |       ^
  5 |   if (breakpoint in theme.breakpoints) {
  6 |     return px(theme.breakpoints[breakpoint as MantineBreakpoint]) as number;
  7 |   }

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment] 2024-09-27 08:58
Please provide a sandbox with a minimal reproduction. Template – https://codesandbox.io/s/mantine-react-template-q4dd5d?file=/src/App.js

**Comment by rishabh-te** [comment] 2024-09-27 10:52
Hi here is code .

https://codesandbox.io/p/sandbox/mantine-react-template-forked-ghx4rr

Thanks

**Comment by jackkweyunga** [comment] 2024-09-27 13:34
Am facing same issue. Am using exact versions as described in the issue.

**Comment by rishabh-te** [comment] 2024-09-27 13:40
@jackkweyunga switching to [7.12.2](https://www.npmjs.com/package/@mantine/carousel/v/7.12.2) might solve this problem
instead of 7.13.0

**Comment by jackkweyunga** [comment] 2024-09-27 14:37
> @jackkweyunga switching to [7.12.2](https://www.npmjs.com/package/@mantine/carousel/v/7.12.2) might solve this problem instead of 7.13.0

This worked. Thanks @rishabh-te

**Comment by llezhava** [comment] 2024-10-01 14:30
I upgraded @mantine/core .etc mantine libraries to 7.13.1 and it worked.

**Comment by rtivital** [comment] 2024-10-02 12:36
I cannot reproduce the issue with 7.13.1 – https://codesandbox.io/p/sandbox/mantine-react-template-forked-36fvdc
It seems like it has been already resolved in the current version. To resolve the issue, update dependencies to the latest version and make sure that all `@mantine/` packages have the same version in package.json.

**Closed by rtivital** 2024-10-02 12:36 UTC
