### ISSUE TITLE
Modal closeOnClickOutside not working

### ISSUE THREAD

**Issue by hunterwilhelm** [mantinedev/mantine#2458] opened 2022-09-15 16:07 UTC
### What package has an issue

@mantine/core

### Describe the bug

closeOnClickOutside is no longer working for the Modal component.

Perhaps caused by this bug fix?
https://github.com/mantinedev/mantine/commit/92305e227ef4c6a058e935937c5ba3623380e7ae 

### What version of @mantine/hooks page do you have in package.json?

5.3.2

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/mantine-modal-closeonclickoutside-bug-f12rek

### Do you know how to fix the issue

No

**Comment by rickmoens** [comment] 2022-09-16 14:12
Indeed it is caused by setting the `z-index` to `-1` in 92305e227ef4c6a058e935937c5ba3623380e7ae

**Comment by DaniloHP** [comment] 2022-09-16 23:27
Yep, noticed this too. You can even see it in the docs for Modal. [This specific example](https://mantine.dev/core/modal/#remove-title-and-close-button) actually soft locks the page because **`esc` to close modal doesn't seem to be working either** so there's no way to close that modal! This is pretty urgent IMO

**Comment by rickmoens** [comment] 2022-09-17 09:43
A fix is to set the `z-index` of the `inner` element to `-1` and revert the `z-index` of the `overlay` element.  The scroll bar can then be used again, the only downside is that it is behind the overlay. See the [Codesandbox](https://codesandbox.io/s/mantine-core-2458-4geo7j?file=/src/App.js).

**Comment by rtivital** [comment] 2022-09-17 10:34
Fixed in 5.3.3

**Closed by rtivital** 2022-09-17 10:34 UTC

**Comment by chingiz19** [comment] 2023-01-13 23:16
I think bug is back on 5.9.5

**Comment by chingiz19** [comment] 2023-01-13 23:34
I think bug is back at least on 5.9.5

**Comment by ethannov** [comment] 2024-04-19 03:40
I agree, I think the bug is back. Clicking outside of my modal is not closing it.
