### ISSUE TITLE
useHover, useMouse, other hooks have a type error for refs

### ISSUE THREAD

**Issue by QuinnStraus** [mantinedev/mantine#7252] opened 2024-12-12 23:27 UTC
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.15.1

### What package has an issue?

@mantine/hooks

### What framework do you use?

Next.js

### In which browsers you can reproduce the issue?

Chrome

### Describe the bug

The type signature for the ref objects returned from the hooks is RefObject<T | null> rather than RefObject<T>, creating the following type error when the refs are passed into the ref prop of an html element:
`Type 'RefObject<HTMLDivElement | null>' is not assignable to type 'RefObject<HTMLDivElement>'.`
The hooks seem to still work as expected.

### If possible, include a link to a codesandbox with a minimal reproduction

https://codesandbox.io/p/sandbox/mantine-react-template-forked-lnp22m

### Possible fix

Return the hook type signature to RefObject<T>.

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by QuinnStraus** [comment] 2024-12-12 23:49
Update: this seems to be an issue with react 19 changing the return type of useRef and the ref prop on html elements, since I had upgraded my project to mantine 7.15 but not react 19 yet. Codesandbox seems to also not have been using the react 19 types, causing the issue to reproduce there.

**Comment by jonavila** [comment] 2024-12-14 01:15
Same, issue for me with existing `useElementSize`, `useHover` and a few others.

**Comment by rtivital** [comment] 2024-12-15 19:02
I cannot reproduce the issue https://codesandbox.io/p/sandbox/mantine-react-template-forked-m23r4p
Please provide a sandbox with a minimal reproduction

**Comment by jonavila** [comment] 2024-12-15 20:15
@rtivital The codesanbox link posted with the ticket shows the TS error: https://codesandbox.io/p/sandbox/mantine-react-template-forked-lnp22m

<img width="1658" alt="image" src="https://github.com/user-attachments/assets/14588371-c071-4383-ac20-8bf9c3459c23" />

**Comment by rtivital** [comment] 2024-12-16 05:37
Thanks, I've found the issue with some hooks, fixed it, will be available with the next patch.

**Comment by yiichou** [comment] 2024-12-23 02:31
ship it, please 🙏

**Comment by rtivital** [comment] 2024-12-23 10:15
Fixed in [7.15.2](https://github.com/mantinedev/mantine/releases/tag/7.15.2)

**Closed by rtivital** 2024-12-23 10:15 UTC
Labels: Fixed patch
