### ISSUE TITLE
Incorrect Title of the embed when link is shared in Discord.

### ISSUE THREAD

**Issue by PhantomKnight287** [mantinedev/mantine#2793] opened 2022-10-25 06:30 UTC
### Link to the page where something nasty is located

https://mantine.dev

### Exact quote of what is wrong

If you share this link `https://mantine.dev` on discord, the embed shows the title `AppShell Demo` instead of `Mantine`.

![image](https://user-images.githubusercontent.com/76196237/197699117-10775d28-e8dc-4a19-8ebf-203e0db2352e.png)

**Comment by LeHvass** [comment] 2022-10-25 17:17
Hi @rtivital,

I've been able to recreate this locally with `npm run docs:build` (see image).
<img width="1327" alt="Screenshot 2022-10-25 at 18 44 52" src="https://user-images.githubusercontent.com/5744255/197839428-20670a53-2c3a-45bd-a0aa-8ce62e835f9a.png">

However, issue appears to be inconsistent (doesn't happen on every build) and related to some kind of race condition.

A very similar sounding issue with the `gatsy-plugin-material-ui` package was being discussed here [https://github.com/hupe1980/gatsby-plugin-material-ui/issues/80#issuecomment-965909424](https://github.com/hupe1980/gatsby-plugin-material-ui/issues/80#issuecomment-965909424).

@rtivital, it seems like the issue is likely with the `gatsy-ssr.js` file, but I am personally unsure how to proceed. If this turns out to be difficult and/or time consuming to nail down, we may be better off moving to the new Gatsby Head API as the `gatsby-plugin-react-helmet` is anyway to be deprecated. (Would require moving gatsby package from 4.14 to at least 4.19 (current version 4.24).
![Screenshot 2022-10-25 at 18 59 50](https://user-images.githubusercontent.com/5744255/197839521-9ef711c6-f6d2-44b5-ab63-7ea402fc195e.png)

What are your thoughts?

**Comment by rtivital** [comment] 2022-10-25 18:17
I would rather migrate to new Gatsby Head API, it would be great if you can send a PR

**Comment by LeHvass** [comment] 2022-10-26 14:37
I'm unsure when I'll have the bandwidth to look at this, so for now, let's leave it open for anyone to jump on.

**Comment by rtivital** [comment] 2022-10-27 16:58
Okay, help is still wanted then

**Comment by rtivital** [comment] 2023-01-17 07:13
Fixed

**Closed by rtivital** 2023-01-17 07:13 UTC
Labels: completed
