### ISSUE TITLE
`dot={false}` but `dot` in indicator docs.

### ISSUE THREAD

**Issue by GZTimeWalker** [mantinedev/mantine#2407] opened 2022-09-10 08:52 UTC
### Link to the page where something nasty is located

https://mantine.dev/core/indicator/

### Exact quote of what is wrong

<img width="839" alt="截屏2022-09-10 16 50 49" src="https://user-images.githubusercontent.com/28180262/189476168-698cdf92-145c-47cb-8d3a-c1c6d93099db.png">

`dot={false}` but `dot` ?

**Comment by zhulien-ivanov** [comment] 2022-09-10 10:13
Should be fixed with: https://github.com/mantinedev/mantine/pull/2409. The `Indicator` main demo is not very clean, though, so I guess it should be refactored a bit.

**Comment by rtivital** [comment] 2022-09-10 10:49
The issue is fixed, it will be deployed with next patch

**Closed by rtivital** 2022-09-10 10:49 UTC
