### ISSUE TITLE
Installing Modals package cause's Mantine/ssr to break on Remix . 

### ISSUE THREAD

**Issue by Leenus533** [mantinedev/mantine#1276] opened 2022-04-18 09:38 UTC
### What package has an issue

@mantine/modals

### Describe the bug

installing the modals package cause's SSR injection to fail on build on Remix. 

This error persists even after removing the package and uninstalling it. Potentially due to caching on Remix.  This  error was caused on the Remix/Vercel build.  An example showcasing the error can be seen here.
After the package has been installed - https://main-client-b4dce13og-leenus.vercel.app/
before the package has been installed -  https://main-client-leenus.vercel.app/

### In which browser did the problem occur

Firefox 

### Do you know how to fix the issue

No

**Comment by iDavidB** [comment] 2022-04-25 11:25
Could you create a codesandbox that reproduces this issue? It seems to work fine for me.
https://codesandbox.io/s/busy-wind-wqqoyi?file=/app/root.tsx

Unless i'm missing something?

**Comment by tsar-boomba** [comment] 2022-05-01 00:36
I'm having a similar problem in Next.js, the primary color and colorScheme is rendered incorrectly, only in my custom components. Only started happening after installing modals. In the example below, the orange should be darker because I'm in dark theme, but its light, and my form section component renders the completely wrong theme.

![Screenshot_370](https://user-images.githubusercontent.com/77396670/166127206-daa258fd-92d4-4497-aed3-6810eefefc5f.png)
.

**Comment by rtivital** [comment] 2022-07-25 10:34
Should be fixed in 5.0, `@emotion/react` and `@emotion/server` packages are now required to be installed as peer dependencies

**Closed by rtivital** 2022-07-25 10:34 UTC
Labels: bug
