### ISSUE TITLE
Rating component value is mutable even with readOnly prop

### ISSUE THREAD

**Issue by gulebi** [mantinedev/mantine#4525] opened 2023-07-11 04:36 UTC
### What package has an issue

@mantine/core

### Describe the bug

When the value of a rating element changes, it changes with an animation, but when the `readOnly` prop is added, there is no animation and the value still changes.

### What version of @mantine/hooks page do you have in package.json?

6.0.16

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by rtivital** [comment] 2023-07-11 05:00
Based on the demo from the docs, the `readOnly` prop seems to be working correctly – it prevents user from interacting with the input – https://mantine.dev/core/rating/#read-only

Please provide a sandbox that reproduces the issue

**Comment by gulebi** [comment] 2023-07-11 18:28
Here is a link to [codesandbox](https://codesandbox.io/s/agitated-pare-69gdtz?file=/src/App.tsx), although the `@mantine/core` version is different, the bug is present on both version `6.0.8` and `6.0.16`.

**Comment by rtivital** [comment] 2023-07-18 05:26
Fixed in 6.0.17

**Closed by rtivital** 2023-07-18 05:26 UTC
