### ISSUE TITLE
Pressing Escape closes all opened modals/menus/popovers instead of just the last opened one

### ISSUE THREAD

**Issue by fpolic-profico** [mantinedev/mantine#6553] opened 2024-07-19 10:40 UTC
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.11.2

### What package has an issue?

@mantine/core

### What framework do you use?

Vite

### In which browsers you can reproduce the issue?

All

### Describe the bug

If you have opened multiple items such as a modal with a menu/popover inside it, pressing Escape will close all of the mentioned items instead of just the last opened item.

I tested this also with a Select component and Select seems to work as expected. I'll paste the code that reproduces the error in case the link to the sandbox expires or stops working.

```tsx
import '@mantine/core/styles.css';

import React from 'react';

import { MantineProvider, Modal, Menu, Popover, Select } from '@mantine/core';
import { useDisclosure } from '@mantine/hooks';

function Wrapper() {
  const [isModalOpen, modalActions] = useDisclosure(false);
  const [isInnerModalOpen, innerModalActions] = useDisclosure(false);

  return (
    <>
      <button onClick={modalActions.open}>Open modal</button>
      <Modal opened={isModalOpen} onClose={modalActions.close}>
        From inside modal
        <button onClick={innerModalActions.open}>Open inner modal</button>
        <Modal opened={isInnerModalOpen} onClose={innerModalActions.close}>
          From inside inner modal
        </Modal>
        <Menu>
          <Menu.Target>
            <button>Menu</button>
          </Menu.Target>
          <Menu.Dropdown>
            <Menu.Item>Copy</Menu.Item>
            <Menu.Item>Duplicate</Menu.Item>
            <Menu.Item>Delete</Menu.Item>
          </Menu.Dropdown>
        </Menu>
        <Select
          label="Your favorite library"
          placeholder="Pick value"
          data={['React', 'Angular', 'Vue', 'Svelte']}
          mb="xs"
        />
        <Popover>
          <Popover.Target>
            <button>Popover</button>
          </Popover.Target>
          <Popover.Dropdown>
            <h1>from inside popover</h1>
          </Popover.Dropdown>
        </Popover>
      </Modal>
    </>
  );
}

export default function App() {
  return (
    <MantineProvider>
      <Wrapper />
    </MantineProvider>
  );
}
```

### If possible, include a link to a codesandbox with a minimal reproduction

https://stackblitz.com/edit/react-whwymk?file=src%2FApp.js

### Possible fix

My suggestion would be to mimic the behaviour of the Select component and close just the last opened item.

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment] 2024-07-19 12:19
Duplicate of https://github.com/mantinedev/mantine/issues/6528

**Closed by rtivital** 2024-07-19 12:19 UTC
