### ISSUE TITLE
Menu component aria-hidden attribute causes accessibility issue observed in Brave Browser

### ISSUE THREAD

**Issue by hogank3** [mantinedev/mantine#6690] opened 2024-08-16 21:12 UTC
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.12.1

### What package has an issue?

@mantine/core

### What framework do you use?

Vite

### In which browsers you can reproduce the issue?

Other, I will specify in the bug description

### Describe the bug

I am encountering an accessibility issue when using the [Menu](https://mantine.dev/core/menu/) component from Mantine UI in the Brave browser. The error message is as follows:

```error
Blocked aria-hidden on a <div> element because the element that just received focus must not be hidden from assistive technology users. Avoid using aria-hidden on a focused element or its ancestor. Consider using the inert attribute instead, which will also prevent focus. For more details, see the aria-hidden section of the WAI-ARIA specification at https://w3c.github.io/aria/#aria-hidden. 
```

This issue does not occur in Chrome. It seems that Brave enforces accessibility rules more strictly.

Steps to Reproduce:

Visit the Mantine UI Menu [documentation](https://mantine.dev/core/menu/) in the Brave browser.
Open any example menu.
Observe the console for the accessibility error.

### Possible fix

Consider using the inert attribute instead of aria-hidden to prevent focus on hidden elements.

### Self-service

- [X] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment] 2024-08-17 05:36
Duplicate of #6644

**Closed by rtivital** 2024-08-17 05:36 UTC
