### ISSUE TITLE
Array form validation is not reactive

### ISSUE THREAD

**Issue by macist-m** [mantinedev/mantine#1394] opened 2022-05-05 17:35 UTC
### What package has an issue

@mantine/form

### Describe the bug

Hello, when creating forms with "use-form lists" validation of the inputs are not reactive, meaning if there is an error on empty input box, filling it out is not clearing out the error message, yet if I submit the form again it clears out....

This happens with 3rd party lib like yup or with plain validation, it does not matter in my case...

This is not the case with regular forms with no array of inputs.

Hopefully I was able to explain it :)

Thanks

### In which browser did the problem occur

chrome/safari

### Do you know how to fix the issue

No

**Comment by rtivital** [comment] 2022-05-08 07:24
I cannot reproduce this, can you send a sandbox?

**Comment by macist-m** [comment] 2022-05-08 11:08
> I cannot reproduce this, can you send a sandbox?

Sure -> https://codesandbox.io/s/heuristic-rui-c6pxm5

**Comment by rtivital** [comment] 2022-05-08 13:39
So the issue is that when field changes the error is not cleared, right?

**Comment by macist-m** [comment] 2022-05-08 14:54
> So the issue is that when field changes the error is not cleared, right?

Yup, exactly...

**Comment by OlegGulevskyy** [comment] 2022-05-10 22:03
Hello,
can I take this one? I am looking for a place to dip my toes in open source so that would be my first attempt :)

**Comment by rtivital** [comment] 2022-05-11 06:09
sure

**Comment by rtivital** [comment] 2022-05-15 09:01
Fixed in 4.2.5, thanks @OlegGulevskyy

**Closed by rtivital** 2022-05-15 09:01 UTC
Labels: help wanted, bug

**Comment by macist-m** [comment] 2022-05-15 19:27
@OlegGulevskyy Thanks a lot...
