### ISSUE TITLE
Controlled popover doesn't close on click away

### ISSUE THREAD

**Issue by stuymedova** [mantinedev/mantine#7079] opened 2024-11-05 13:10 UTC
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.13.4

### What package has an issue?

@mantine/core

### What framework do you use?

Vite

### In which browsers you can reproduce the issue?

Chrome

### Describe the bug

I expect onClose to get called on click outside, but it doesn't happen. Repro (taken from the docs and adjusted slightly):
```jsx
function Demo() {
  const [opened, { close, toggle }] = useDisclosure(false);

  return (
    <Popover
        width={200}
        position="bottom"
        withArrow={true}
        shadow="md"
        opened={opened}
        closeOnClickOutside={true}
        closeOnEscape={true}
        onClose={() => {
            console.log('ok'); // on click outside onClose doesn't get called, nothing gets printed!
            close();
        }}
    >
        <Popover.Target>
            <Button onClick={toggle}>
                {'Click to see popover'}
            </Button>
        </Popover.Target>
        <Popover.Dropdown style={{ pointerEvents: 'none' }}>
            <Text size="sm">{'This popover is shown when user clicks the target element'}</Text>
        </Popover.Dropdown>
    </Popover>
  );
}
```

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by rtivital** [comment] 2024-11-05 13:21
Duplicate of https://github.com/mantinedev/mantine/issues/7019
See the linked issue to learn more

**Closed as completed by rtivital** 2024-11-05 13:21 UTC
