### ISSUE TITLE
Drawer component on vercel production throws client side error

### ISSUE THREAD

**Issue by oliverkidd** [mantinedev/mantine#4668] opened 2023-08-17 09:03 UTC
### What package has an issue

@mantine/core

### Describe the bug

The drawer component is working fine on local development.

when deploying to vercel and toggling the drawer it is producing a client side error "TypeError: undefined is not an object (evaluating 'e.transitionProperty')"

I have tried allowing the drawer to stay mounted but that makes no change.

### What version of @mantine/hooks page do you have in package.json?

6.0.19

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by rtivital** [comment] 2023-08-17 09:59
Duplicate of https://github.com/mantinedev/mantine/issues/4548

**Closed by rtivital** 2023-08-17 09:59 UTC

**Comment by oliverkidd** [comment] 2023-08-17 12:25
Thanks for the quick response. Didn't see the existing thread - sorry for the duplicate
