### ISSUE TITLE
NumberInput handles big number in an unexpected way

### ISSUE THREAD

**Issue by Benjaminsson** [mantinedev/mantine#7033] opened 2024-10-25 12:51 UTC
### Dependencies check up

- [x] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.13.4

### What package has an issue?

@mantine/core

### What framework do you use?

Vite

### In which browsers you can reproduce the issue?

Chrome

### Describe the bug

Big numbers `10_000_000_000_000` and above gets reset when incrementing it.

https://github.com/user-attachments/assets/762daa0e-96c6-4bdc-afcb-4c822deb370b

I don't know if that is expected behaviour but it gets a little extra weird if you have a max amount. Then maybe it should default to the max amount?

https://github.com/user-attachments/assets/a4d460b3-1497-49ff-bdef-8c75d87b5a92

Not sure if this is related but the number -0 defaults to 0 while just a regular 0 defaults to what you defined in the min prop. 

https://github.com/user-attachments/assets/93317567-6685-432f-b442-308d4176371c

### If possible, include a link to a codesandbox with a minimal reproduction

https://codesandbox.io/p/sandbox/focused-dawn-zrsz64

### Self-service

- [ ] I would be willing to implement a fix for this issue

**Comment by Kenzo-Wada** [comment] 2024-10-25 15:29
I think this is a issue of react-number-format

**Comment by rtivital** [comment] 2024-11-16 13:36
I've implemented a fix for this in the next patch. The issue is that numbers larger than Number.MAX_SAFE_INTEGER cannot be correctly incremented/decremented with the standard js operators (`-`/`+`). It would require a lot of code and possibly a third-party library to support this feature, so currently it is not planned to be implemented. Instead, starting from the next patch 7.14.1, increment/decrement controls will be hidden when the value cannot be safely incremented/decremented.

**Comment by rtivital** [comment] 2024-11-16 15:21
Fixed in [7.14.1](https://github.com/mantinedev/mantine/releases/tag/7.14.1)

**Closed by rtivital** 2024-11-16 15:21 UTC
Labels: Fixed patch
