### ISSUE TITLE
DatePicker & TimeInput expose incorrect FormData.

### ISSUE THREAD

**Issue by ChazUK** [mantinedev/mantine#2795] opened 2022-10-25 16:09 UTC
### What package has an issue

@mantine/dates

### Describe the bug

When trying to use Mantine Date inputs with a framework like Remix which favours sending the pure HTML Form Data to the server to be processed, DatePicker and TimeInput do not expose the correct values.

DatePicker sends the formatted Date which is seen in the input field ont he presentation side, and TimeInput only sends the hours.

Ideally the `.toDateString()`, `.toTimeString()` or even `.toISOString` should be returned.

### What version of @mantine/hooks page do you have in package.json?

5.5.2

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/mantine-date-form-values-lpl7lw

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Possible fix

The input field should not have it's value set to the formatted date/time, instead there should be a shadow input field showing the presentation data.

**Comment by ChazUK** [comment] 2022-10-25 16:13
Also, it would be great if the form defaulted the name of the field to the variable name that it was give in the useForm init

**Comment by rtivital** [comment] 2022-10-25 18:14
The issue is fixed, it will be available with 6.0 release with dates package revamp

**Comment by ChazUK** [comment] 2022-10-25 23:11
@rtivital awesome! I did search for the issue but could not find it posted anywhere. Do you know when 6.0 will be released, I couldn’t see an alpha or beta tag.

And do you know if the `name` attribute will also be added?

**Comment by rtivital** [comment] 2022-10-26 07:40
Yes, the correct name attribute will be added to all date inputs. There is no ETA for 6.0 yet.

**Comment by ErnieBernie10** [comment] 2022-11-28 16:48
Could you suggest a work around for the time being? I tried setting the value manually with ref attribute but it gets overwritten instantly onChange by the datepicker component.

**Comment by rtivital** [comment] 2022-11-28 16:49
You can use experimental dates package, it should be working fine – https://rtivital.github.io/mantine-dates-6/

**Comment by ErnieBernie10** [comment] 2022-11-28 16:53
Awesome. Thanks!

**Comment by rtivital** [comment] 2023-03-03 06:52
Fixed in 6.0

**Closed by rtivital** 2023-03-03 06:52 UTC
Labels: completed-in-6.0
