### ISSUE TITLE
[v6] - Multiple modals briefly show empty modal when closed

### ISSUE THREAD

**Issue by justinsmid** [mantinedev/mantine#3623] opened 2023-02-27 14:20 UTC
### What package has an issue

@mantine/modals

### Describe the bug

When multiple modals are opened at once, and you close them using `modals.closeAll`, an empty modal is briefly shown at the top of the screen:

![image](https://user-images.githubusercontent.com/34271675/221587339-3f71af6d-c7da-4be2-95b8-035a3f420805.png)

This only seems to happen when **multiple** modals are opened. It closes correctly when only one modal is opened.

Not sure if this is v6-specific or maybe even `6.0.0-alpha.5`-specific. In the codesandbox I get `RangeError: Maximum call stack size exceeded` when trying to reproduce this on **either** latest v6 (`6.0.0-alpha.7`) or latest v5 (`5.10.5`)

### What version of @mantine/hooks page do you have in package.json?

6.0.0-alpha.5

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/hungry-feather-mymohv?file=/src/App.tsx

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by rtivital** [comment] 2023-02-27 14:46
@cyantree another bug related to your changes modals

**Comment by cyantree** [comment] 2023-02-27 21:54
Thanks for reporting. See my PR #3625 for a fix and a reason why it worked previously but also wasn't fully correct.

**Comment by rtivital** [comment] 2023-03-08 07:41
Fixed in 6.0

**Comment by rtivital** [comment] 2023-03-08 07:41
@justinsmid please confirm that your issue was resolved

**Closed by rtivital** 2023-03-08 07:41 UTC

**Comment by justinsmid** [comment] 2023-03-08 08:48
This immediate issue is indeed fixed, thanks!

However, the new version still works kind of awkwardly in my opinion. Now, when you close multiple modals using `closeAll`, you see each modal disappear and the previous one re-appear for a little bit before it disappears.

(https://codesandbox.io/s/hungry-feather-mymohv?file=/src/App.tsx)

I think it might be nicer to have them all appear to be closed instantly.
Looking at the PR, I think the `.reverse()` [here](https://github.com/cyantree/mantine/blob/fbb181feffeaa686b4fe113fdc474494fbf15ebf/src/mantine-modals/src/reducer.ts#LL71C19-L71C19) would be the cause of this behavior. Closing them bottom-to-top should probably resolve this.

**Comment by rtivital** [comment] 2023-03-08 12:00
@cyantree can you take a look at this?

**Comment by cyantree** [comment] 2023-03-08 20:12
Yep.

`.reverse()` doesn't seem to be the issue as I can also reproduce it without it.

The issue seems to be the following:
- Let's assume you open Modals 1, 2, 3, 4 (in this order)
- You'll close Modal 4
- So the Modal stack reduces to Modals 1, 2, 3
- Modal 3 becomes the current one and will be displayed (that's where the flickering comes up)
- Because Modal 4 has an `onClose()` handler that closes all modals Modal 3 will be kept around during the exit transition

What can we do to handle this?
a) A bit ugly solution might be using kind of a debounce here:
- When closing multiple modals shortly in a row (as done here), the first one of this row will be kept as latest modal

b) Another option (which might fit this usecase better) can be:
- When trying to close the Modal don't actually close it but only trigger a callback (like "onBeforeClose()". This callback might then be used to prevent the default behaviour and instead call `closeAll()`. This keeps the current Modal as the last one and therefore doesn't trigger this flickering

c) We might remove this "keep the last Modal around" functionality and implement the transition in a different way
d) We might delay showing the current modal which in this case might lead to it never being displayed. However this is a bit like a debounce and might also interfere with the "keep the last Modal around" logic

Do you have any other ideas?

**Comment by cyantree** [comment] 2023-03-09 16:07
Please have a look at this modified example:
https://codesandbox.io/s/angry-moser-jflkwu?file=/src/ModalContent.tsx:312-355

When you close the nested modal there's now a timeout of 1.5sec before `closeAll()` gets called.
This shows that before every modal gets closed at first the current one gets closed and the next one becomes active.
This results in the glitch.

Therefore in my opinion a callback `onBeforeClose()` would help because in this case closing the nested modal wouldn't actually close it but (after a timeout of 1.5sec) would trigger `closeAll()` that does the closing.

I've also added button to the nested modal that kind of simulates this by simply calling `closeAll()`.

`onBeforeClose()` may also have other uses like being able to implement a "do you really want to close?" functionality or something like "please wait while we're processing your request" - so some async closing.
The integration could be like this:
- Closing via X or outside click would trigger the callback (as it's considered a user initiated closing)
- Implementing the callback and returning `false` (maybe as sync or async callback) would cancel the closing
- Calling `closeModal()` or `closeAll()` directly however wouldn't call this (as it's consideres a code initiated closing)
