### ISSUE TITLE
RichText Editor Toolbar Style Toggle Not Working

### ISSUE THREAD

**Issue by harrycarp** [mantinedev/mantine#1789] opened 2022-07-14 04:35 UTC
### What package has an issue

@mantine/rte

### Describe the bug

When using the toolbar, default or custom, toggling a style by clicking on a button only works one-way (can activate style, cannot deactivate). When using hot-keys, style toggling works both ways.

The JavaScript console produces an error originating from QuillJS. 
```
addRange(): The given range isn't in document.
```

The project is using NextJS TypeScript, and the guide provided was followed to initiate the project.
I have searched high-and-low in both relation to Mantine RTE and QuillJS, and the fixes provided ([provided empty modules](https://github.com/quilljs/quill/issues/1940) etc.) did not work.

If anyone has any potential fixes that would be wonderful :)

### In which browser did the problem occur

Chrome

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/aged-forest-6tfrtb?file=/package.json

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

**Comment by rtivital** [comment] 2022-07-17 09:01
Duplicate of https://github.com/mantinedev/mantine/issues/1386

**Closed by rtivital** 2022-07-17 09:01 UTC
Labels: bug

**Comment by chadmuro** [comment] 2022-07-27 14:27
I am currently having the same issue with Next version 12.2.3 and version 5.0.0 of @mantine/core @mantine/hooks @mantine/next @mantine/rte. Have you figured out what the issue with this may be?

I tried to recreate this issue in a new sandbox, but it was working fine there.

By the way, the previous error `addRange(): The given range isn't in document` seems to have been fixed when I updated Mantine to version 5.0.0.

**Comment by chadmuro** [comment] 2022-07-30 08:57
In case anyone is having the same issue, I managed to get it working properly by updating my `next.config.js` file following the same configuration as the [Mantine Next Template.](https://github.com/mantinedev/mantine-next-template)

```js
const withBundleAnalyzer = require('@next/bundle-analyzer')({
  enabled: process.env.ANALYZE === 'true',
});

module.exports = withBundleAnalyzer({
  reactStrictMode: false,
  eslint: {
    ignoreDuringBuilds: true,
  },
});
```

**Comment by rtivital** [comment] 2022-07-30 09:27
Well, seems like the error may be associated with react strict mode
