### ISSUE TITLE
[@mantine/dates] Cannot read properties of undefined (reading 'getFullYear')

### ISSUE THREAD

**Issue by arpitprod** [mantinedev/mantine#2020] opened 2022-08-05 13:18 UTC
### What package has an issue

@mantine/dates

### Describe the bug

If I selected `minDate` id today and date picker default value is past month date and when we click on date picker input box it's breaking code.

I understood issue but my requirement is - 

We will show old date in edit field and if we want to choose another date it should show only future dates.

If `minDate` is added and state value is past month/year date then it should show value in input box and when we open date picker then it should open minDate's month 

### What version of @mantine/hooks page do you have in package.json?

4.2.12

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/mantine-date-picker-mzpw37

**Comment by rtivital** [comment] 2022-08-05 13:28
The issue is fixed in 5.0 – https://codesandbox.io/s/mantine-date-picker-forked-co3oyx

**Closed by rtivital** 2022-08-05 13:28 UTC
Labels: bug

**Comment by arpitprod** [comment] 2022-08-05 13:48
Thanks, I will update

and when we open date picker, it should show minDate's month.
It's showing value month now. and we can't change month here.

![Screenshot 2022-08-05 at 7 12 35 PM](https://user-images.githubusercontent.com/19798516/183089700-81d80299-cb53-43ba-8e25-77a22811d348.png)

and when we click outside, date changing to minDate. but maybe end user will not click 2nd time for change date. They will think this is a bug.

**Comment by arpitprod** [comment] 2022-08-05 13:52
If I remove `allowFreeInput` props then date not updating to minDate after close date picker also.

**Comment by rtivital** [comment] 2022-08-05 13:54
Yeah, I'll see what can be do with that, I think we can show next month arrow if current month is before minDate. You can disable value transforming with `fixOnBlur={false}` prop.

**Comment by arpitprod** [comment] 2022-08-05 14:09
Just a Question, I didn't see code,
I don't know, How much complex is it

If date value is old and we are adding minDate (new) then we can't show minDate default month when open date picker ?
