### ISSUE TITLE
Number input doesnt reset state when form submitted with ENTER

### ISSUE THREAD

**Issue by tombohub** [mantinedev/mantine#3145] opened 2022-12-08 12:48 UTC
### What package has an issue

@mantine/core

### Describe the bug

Type all the numbers in inputs and submit form with ENTER key.
The last input doesn't reset.

If using the ref to focus on first input after the ENTER submit then the first input doesn't reset to zero.

in this handler:

```typescript
  function handleSubmit(e) {
    e.preventDefault();
    resetMeasurements();
    // focus();
  }
```

### What version of @mantine/hooks page do you have in package.json?

5.9.2

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/setstate-last-input-fail-with-mantine-g7yx0c?file=/src/MeasurementInput.jsx

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by rtivital** [comment] 2022-12-08 12:50
Duplicate of https://github.com/mantinedev/mantine/issues/3059

**Closed by rtivital** 2022-12-08 12:50 UTC
