### ISSUE TITLE
Problem with list on RichTextEditor

### ISSUE THREAD

**Issue by marcelo130102** [mantinedev/mantine#1706] opened 2022-06-30 22:43 UTC
### What package has an issue

@mantine/rte

### Describe the bug

![image](https://user-images.githubusercontent.com/70810134/176790209-328e5855-f037-484b-8968-5c4fba6ba227.png)
I'm using the example of Mantine about de RTE. But when I try to add a list, this error appears.

### In which browser did the problem occur

OperaGX, Chrome, Safari, Firefox

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

**Comment by rtivital** [comment] 2022-07-01 07:53
Duplicate of #1508

**Closed by rtivital** 2022-07-01 07:53 UTC
Labels: bug
