### ISSUE TITLE
Remix and Mantine (latest) failed with AWS deployment (Grunge-Stack)

### ISSUE THREAD

**Issue by JasonWeiseUnreal** [mantinedev/mantine#1694] opened 2022-06-28 09:37 UTC
### What package has an issue

@mantine/core

### Describe the bug

Mantine appears to work fine with Remix (Grunge-Stack) on local development environment but when deployed to AWS `{"message":"Internal Server Error"}` is the result when viewing the site.

I have completely removed Mantine from the project and the deployment works and the site on AWS works as expected with the default Remix "Grunge-Stack".

If I replace my entry.server.tsx with the following it works fine still when deployed (as per Matine Remix instructions) - Note without ANY Mantine components on any pages:
```
import { renderToString } from 'react-dom/server';
import { RemixServer } from '@remix-run/react';
import type { EntryContext } from '@remix-run/node';
import { injectStylesIntoStaticMarkup } from '@mantine/ssr';

export default function handleRequest(
  request: Request,
  responseStatusCode: number,
  responseHeaders: Headers,
  remixContext: EntryContext
) {
  const markup = renderToString(<RemixServer context={remixContext} url={request.url} />);
  responseHeaders.set('Content-Type', 'text/html');

  return new Response(`<!DOCTYPE html>${injectStylesIntoStaticMarkup(markup)}`, {
    status: responseStatusCode,
    headers: responseHeaders,
  });
}
```

... but...
As soon as I even add a Mantine <Button> component to the page the deployment to AWS appears to work fine with no errors but the site shows `{"message":"Internal Server Error"}` again.

I have debugged on AWS and it appears to be related to `@mantine/hooks` not being found and throwing an execption.
The interesting thing is, my test only has a single mantine <Button> on the page to try and test what is causing the issue and I am not using an Accordian control anywhere yet is mentioned in the error.

Error Log on AWS:
```
2022-06-28T00:15:37.814Z	undefined	ERROR	Uncaught Exception 	
{
    "errorType": "Runtime.ImportModuleError",
    "errorMessage": "Error: Cannot find module '@mantine/hooks'\nRequire stack:\n- /var/task/node_modules/@mantine/core/cjs/components/Accordion/use-accordion-state/use-accordion-state.js\n- /var/task/node_modules/@mantine/core/cjs/index.js\n- /var/task/index.js\n- /var/runtime/UserFunction.js\n- /var/runtime/Runtime.js\n- /var/runtime/index.js",
    "stack": [
        "Runtime.ImportModuleError: Error: Cannot find module '@mantine/hooks'",
        "Require stack:",
        "- /var/task/node_modules/@mantine/core/cjs/components/Accordion/use-accordion-state/use-accordion-state.js",
        "- /var/task/node_modules/@mantine/core/cjs/index.js",
        "- /var/task/index.js",
        "- /var/runtime/UserFunction.js",
        "- /var/runtime/Runtime.js",
        "- /var/runtime/index.js",
        "    at _loadUserApp (/var/runtime/UserFunction.js:221:13)",
        "    at Object.module.exports.load (/var/runtime/UserFunction.js:279:17)",
        "    at Object.<anonymous> (/var/runtime/index.js:43:34)",
        "    at Module._compile (internal/modules/cjs/loader.js:1085:14)",
        "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)",
        "    at Module.load (internal/modules/cjs/loader.js:950:32)",
        "    at Function.Module._load (internal/modules/cjs/loader.js:790:12)",
        "    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12)",
        "    at internal/main/run_main_module.js:17:47"
    ]
}
```

Do you have any idea why locally mantine is working correctly but seems to have parts stripped with Remix when deployed with the "Grunge-Stack"?

Thanks in advance, I love your UI kit and would love to use it in a new project if I can resolve this issue.

### In which browser did the problem occur

All

### Do you know how to fix the issue

No

**Comment by rtivital** [comment] 2022-06-28 11:41
Seems like you did not install `@mantine/hooks` package.

**Comment by JasonWeiseUnreal** [comment] 2022-06-28 19:26
Hi @rtivital 

Yeah sure have (installed `@mantine/hooks`) , otherwise it wouldn't work locally I guess, it is only once deployed it doesn't work.
package.json:
```
 "dependencies": {
    "@architect/architect": "^10.3.3",
    "@architect/functions": "^5.1.0",
    "@mantine/core": "^4.2.11",
    "@mantine/hooks": "^4.2.11",
    "@mantine/ssr": "^4.2.11",
    "@remix-run/architect": "^1.6.1",
    "@remix-run/node": "^1.6.1",
    "@remix-run/react": "^1.6.1",
    "@remix-run/server-runtime": "^1.6.1",
    "bcryptjs": "2.4.3",
    "cuid": "^2.1.8",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "tiny-invariant": "^1.2.0",
    "tabler-icons-react": "^1.51.0"
  },
  "devDependencies": {
    "@faker-js/faker": "^6.3.1",
    "@remix-run/dev": "^1.6.1",
    "@remix-run/eslint-config": "^1.6.1",
    "@testing-library/cypress": "^8.0.3",
    "@testing-library/jest-dom": "^5.16.4",
    "@testing-library/react": "^12.1.5",
    "@testing-library/user-event": "^14.2.0",
    "@types/architect__functions": "^3.13.6",
    "@types/bcryptjs": "2.4.2",
    "@types/eslint": "^8.4.3",
    "@types/react": "^17.0.45",
    "@types/react-dom": "^17.0.17",
    "@vitejs/plugin-react": "^1.3.2",
    "c8": "^7.11.3",
    "cross-env": "^7.0.3",
    "cypress": "^10.0.3",
    "esbuild": "^0.14.43",
    "eslint": "^8.17.0",
    "eslint-config-prettier": "^8.5.0",
    "happy-dom": "^5.2.0",
    "mock-aws-s3": "^4.0.2",
    "msw": "^0.42.1",
    "npm-run-all": "^4.1.5",
    "prettier": "^2.6.2",
    "prettier-plugin-tailwindcss": "^0.1.11",
    "start-server-and-test": "^1.14.0",
    "tailwindcss": "^3.1.0",
    "ts-node": "^10.8.1",
    "typescript": "^4.7.3",
    "vite-tsconfig-paths": "^3.5.0",
    "vitest": "^0.14.1"
  },
```

**Comment by rtivital** [comment] 2022-06-29 07:02
I do not know where the issue is – the error says that it did not install `@mantine/hooks` package, maybe there was an error during packages installation

**Comment by cayter** [comment] 2022-07-03 08:16
The Remix grunge stack is using [arc](https://arc.codes) to compile and deploy your code to AWS Lambda (the generated Remix server.js) + S3 (public folder build).

[arc](https://arc.codes) only supports `npm` as it's installing and hydrating (copying) the node modules into each Lambda handler following npm's way of resolving node modules.

For your current issue, you might wanna check locally with `arc deploy --dry-run` to see why it doesn't correctly hydrate the node modules into your Lambda function handler folder or check if you're facing this same [issue](https://github.com/remix-run/remix/issues/210#issuecomment-992532112).

Aside from that, the way how [arc](https://arc.codes) uploads the node modules now is also not scalable. As soon as you add more dependencies to your Remix project, the Lambda function code size will grow crazily and very soon hit the 250MB Lambda code size limit. This is where you strongly feel the sarcasm of `node_modules` being a black hole.

As for myself, I've moved away from [arc](https://arc.codes) and built my own toolkit which bundles the Remix code into 1 single `server.js` without including node modules as part of the Lambda function and so far our [website](https://baya.biz/) `server.js` is only around 700KB. Hope the above helps.

**Comment by rtivital** [comment] 2022-07-03 08:34
Seems like an issue is not related to Mantine, closing it

**Closed by rtivital** 2022-07-03 08:34 UTC
Labels: bug
