### ISSUE TITLE
Typing into a Select should highlight the matching option

### ISSUE THREAD

**Issue by localhosted** [mantinedev/mantine#1366] opened 2022-05-02 02:53 UTC
### What package has an issue

@mantine/core

### Describe the bug

The `Select` component doesn't scroll-to/highlight option when typing

A select should automatically highlight the option that matches whatever you are typing, just like the native select.

For reference, MUI has this implemented: https://mui.com/material-ui/react-select/#main-content (focus a select and type the first letter of any option)

### In which browser did the problem occur

any

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

**Comment by rtivital** [comment] 2022-05-02 07:59
I do not get the issue, Select highlights value when user searches

https://user-images.githubusercontent.com/10353856/166202849-ed681785-f670-4a8e-9f5e-0db22f82e09f.mov

**Comment by localhosted** [comment] 2022-05-02 13:51
I should have specified it was the "Bare minimum usage example"

In the recording below I start typing after opening the select and no option is highlighted:

https://user-images.githubusercontent.com/8821661/166245044-44e84561-970c-41c4-91ba-29d5e6399f37.mp4

**Comment by rtivital** [comment] 2022-05-02 13:54
Then it is a duplicate of #1084

**Closed by rtivital** 2022-05-02 13:54 UTC
Labels: bug
