### ISSUE TITLE
Some props in the Modal component are forwarded to the DOM element which causes a console error

### ISSUE THREAD

**Issue by fpolic-profico** [mantinedev/mantine#4060] opened 2023-04-12 15:01 UTC
### What package has an issue

@mantine/core

### Describe the bug

I set the Modal component default props in the theme settings: 

<img width="595" alt="Screenshot 2023-04-13 at 09 58 40" src="https://user-images.githubusercontent.com/56958090/231709004-f927272a-b1aa-45a2-bde4-a22bcfa82cfe.png">

`scrollAreaComponent`, `centered` and `closeButtonProps` props get passed down to the DOM element causing an error in the console.

<img width="555" alt="Screenshot 2023-04-12 at 15 45 46" src="https://user-images.githubusercontent.com/56958090/231494579-357b5d33-fce3-4426-ba38-e377f4f34232.png">
<img width="569" alt="Screenshot 2023-04-12 at 15 45 56" src="https://user-images.githubusercontent.com/56958090/231494635-47cd8838-49ad-4899-9c60-ddc342b5e87b.png">
<img width="569" alt="Screenshot 2023-04-12 at 15 46 07" src="https://user-images.githubusercontent.com/56958090/231494680-b28ae016-eb42-4a08-acff-090f3c5ad705.png">
<img width="526" alt="Screenshot 2023-04-12 at 15 46 34" src="https://user-images.githubusercontent.com/56958090/231494894-f043e39b-61aa-479f-a118-3f3c1fa64d7d.png">

Looks like `radius` and `overflow` props also get passed down to the DOM element.

### What version of @mantine/hooks page do you have in package.json?

^6.0.2

### Do you know how to fix the issue

None

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by cyantree** [comment] 2023-04-12 20:07
Unfortunately I can't reproduce this with the latest version.
Can you please provide a sandbox for this?
Also please check your installed version. I fixed some similar issues in #3802 which landed in 6.0.3.

**Comment by fpolic-profico** [comment] 2023-04-13 08:56
Installing a newer version seems to fix the issue. I forgot to check the latest version first, my apologies. Thank you for helping. 🎉

**Closed as completed** 2023-04-13 09:50 UTC
