### ISSUE TITLE
Select onDropdownOpen handler is called everytime search value change

### ISSUE THREAD

**Issue by jCobbSK** [mantinedev/mantine#854] opened 2022-02-18 16:02 UTC
### What package has an issue

@mantine/core

### Describe the bug

When `<Select />` is rendered with `searchable` prop, `onDropdownOpen` handler is called on every input change, even when dropdown remains open.

### In which browser did the problem occur

Chrome

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/admiring-davinci-lo1i6w?file=/src/App.tsx

### Do you know how to fix the issue

Maybe?

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Possible fix

It seems like too simple to be true fix but,
can we just remove `setDropdownOpened(true);` call from `handleInputChange` function in `Select.tsx` and rely that `handleInputFocus` will trigger `setDropdownOpened` when input actually got focus and rendered dropdown?

**Comment by rtivital** [comment] 2022-02-18 17:11
Nope, removing `setDropdownOpened(true)` from `handleInputChange` will result in a possibility that select will be in closed state while user searches, e.g., if it was closed with escape key or by clicking on the input. The problem is only in `onDropdownOpen` function being called, not in opening logic itself.

**Comment by wes337** [comment] 2022-02-19 08:22
In the Select component, there is a wrapper function for the `setDropdownOpened` function. It will _always_ call the `onDropdwonOpen`/`onDropdownClose` callback provided, even if the state value doesn't change.

Could the fix be as simple as:
```
const setDropdownOpened = (opened: boolean) => {
      if (dropdownOpened === opened) {
          // Do nothing
          return
      }
      _setDropdownOpened(opened);
      const handler = opened ? onDropdownOpen : onDropdownClose;
      typeof handler === 'function' && handler();
    };
```

**Comment by rtivital** [comment] 2022-02-19 08:23
Yes, seems like a valid solution

**Closed** 2022-02-19 10:13 UTC
Labels: bug

**Comment by jCobbSK** [comment] 2022-03-03 12:40
Thank you very much for such quick fix 🙌
