### ISSUE TITLE
[@mantine/modals] : Centered modal position changes upon closing inside non-centered ModalsProvider

### ISSUE THREAD

**Issue by Sajarin-M** [mantinedev/mantine#3409] opened 2023-01-23 07:32 UTC
### What package has an issue

@mantine/core

### Describe the bug

When a `modal` that is set to be `centered` is closed while it is inside a non-centered `ModalsProvider`, the top position of the modal moves before it is closed. 

### What version of @mantine/hooks page do you have in package.json?

5.10.1

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/s/centered-modal-flicker-e45l1q?file=/src/App.tsx

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

Yes

### Possible fix

The issue may be caused by the current modal props being immediately removed upon closing the modal. This causes the default props ( which is not centered ) to take control.

**Comment by Sajarin-M** [comment] 2023-01-23 11:59
This flicker effect is also noticeable on the size of the modal. Additionally, I first noticed this issue after the `5.10.1` patch release. It would be helpful to investigate if this patch caused this behavior and if there is a way to resolve it.
here is a preview:
![ezgif-5-06513c6b17](https://user-images.githubusercontent.com/68892162/214034426-e417ba1a-6ad6-413d-b4f5-7bd77f1a0f89.gif)

**Comment by rtivital** [comment] 2023-01-27 07:07
The issue is fixed in v6 – https://v6.mantine.dev/

**Comment by Sajarin-M** [comment] 2023-02-16 06:59
Hi @rtivital 👋,

🙏 Thank you for fixing this issue in v6.

I wanted to inform you that this issue was resolved for me (at least it is not noticeable) when I updated to version `5.10.3`.
However, I have noticed that the issue has reappeared after upgrading to version `5.10.4`. 
I thought it would be helpful to bring this to your attention.

**Comment by rtivital** [comment] 2023-02-16 07:52
@cyantree your PR #3498 broke this, I'll roll it back if you do not provide a fix

**Comment by cyantree** [comment] 2023-02-16 20:15
Thanks for the info @rtivital, I'll have a look at it.

**Comment by rtivital** [comment] 2023-02-26 05:50
Fixed in 5.10.5

**Closed by rtivital** 2023-02-26 05:50 UTC
Labels: completed-in-6.0
