### ISSUE TITLE
Urgent: When page translated, website crashes (stepper)

### ISSUE THREAD

**Issue by Geczy** [mantinedev/mantine#3435] opened 2023-01-27 12:58 UTC
### What package has an issue

@mantine/core

### Describe the bug

https://mantine.dev/core/stepper/

Right click > Translate to any language (i chose russian)

![image](https://user-images.githubusercontent.com/1036968/215092489-3c42b633-da88-4e62-ae61-aa6c71b52947.png)

![image](https://user-images.githubusercontent.com/1036968/215092525-4147736b-7a3e-49f5-83c8-3055e3e16013.png)

Press NEXT, you will see entire site become white, mantine page is crashed

![image](https://user-images.githubusercontent.com/1036968/215092588-6bae3496-da44-43be-bbee-39886128a5d8.png)

### What version of @mantine/hooks page do you have in package.json?

latest, doesn't work on your site either

### If possible, please include a link to a codesandbox with the reproduced problem

https://mantine.dev/core/stepper/

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

**Comment by Geczy** [comment] 2023-01-27 13:02
unsure if other packages have the same issue, but my guess is yes

**Comment by rtivital** [comment] 2023-01-27 13:18
So, why exactly is it urgent?

**Comment by Geczy** [comment] 2023-01-27 13:28
> So, why exactly is it urgent?

for my site i have 10,000 users visiting, and 80% are russian. so, urgent for me as my site is in english, they are always crashing :)

**Comment by rtivital** [comment] 2023-01-27 16:22
Well, then you are welcome to research the issue and propose a fix

**Comment by Geczy** [comment] 2023-01-27 17:15
the fix is here, i can look into a PR 

https://github.com/facebook/react/issues/11538#issuecomment-390386520

**Comment by Geczy** [comment] 2023-01-27 17:49
did a little research, if i remove `mantine-Stepper-steps` element the issue is gone. so the issue is somewhere in the steps display

**Comment by rtivital** [comment] 2023-01-27 17:55
Feel free to submit a PR that will wrap elements that cause issue with `span` tag

**Comment by Geczy** [comment] 2023-01-27 18:05
for anyone having this issue, until the library author wants to fix this, you can fix it like this:

```js
<Stepper.Step
  translate="no"
  label="First step"
  description="Twitch chat account"
>
  <ChatBot />
</Stepper.Step>
```

so i will just be setting translate to no until this is fixed 

thanks

**Comment by DanB-dev** [comment] 2023-02-08 14:52
was a PR for this ever made? otherwise, I can try to fix it.

**Comment by Geczy** [comment] 2023-02-08 14:57
wasnt made !

**Comment by DanB-dev** [comment] 2023-02-08 15:06
> wasnt made !

And to be clear you believe the issue is the same one you referenced (https://github.com/facebook/react/issues/11538#issuecomment-390386520) here

**Comment by DanB-dev** [comment] 2023-02-08 17:46
Spent some time looking into this and it appears to be an issue globally with react and translations. There is a workaround but it makes the app slower to run. Probably not one that's gonna get fixed any time soon since even React Devs say it's not currently possible/worth it

**Comment by rajivchaulagain** [comment] 2023-02-09 05:21
Hey everyone I am using mantine ui stepper and it is awesome !! But I have a little problem so I want is to specify certain route for different steps. 
For example I have three steps :
1. It shows booking details
2. It shows form for checkout
3. payment details.
Now , I have tried to add route but it throws error , how can I implement route so that when I navigate from booking details stepper to checkout stepper I want my route to be changed like "/book/checkout" and continuing with payment by "/book/payment".
            *************** THANKS IN ADVANCE *****************

**Comment by Geczy** [comment] 2023-02-09 13:24
i recommend you use ant design, they dont have crashing of the page issues that the library maintainer refuses to fix 👌🏻 

https://ant.design/components/steps

**Comment by rajivchaulagain** [comment] 2023-02-09 13:36
> i recommend you use ant design, they dont have crashing of the page issues that the library maintainer refuses to fix 👌🏻
> 
> https://ant.design/components/steps

Any solution to my above question?

**Comment by auronsan** [comment] 2023-04-13 02:23
can close this issue caused not happen on last version 6.0.7 @rtivital

**Closed** 2023-04-13 05:29 UTC
Labels: help wanted
