### ISSUE TITLE
Modal's CloseButtonProps does not accept `size` prop

### ISSUE THREAD

**Issue by ronny-lark** [mantinedev/mantine#4793] opened 2023-09-19 12:42 UTC
### What package has an issue

@mantine/modals

### Describe the bug

In Mantine 7, attempting
```
modals.openConfirmModal({
  closeButtonProps: { size: 'xl' }
})
```
Throws a TS error claiming that the prop doesn't exist.

The prop exists on `CloseButton`, which in the docs says it's used in modals.
If adding `@ts-ignore` I can see that the prop does in fact have an affect:
![image](https://github.com/mantinedev/mantine/assets/127736655/2c5c2a48-a3bd-4d41-8616-4edadd31dac1)
![image](https://github.com/mantinedev/mantine/assets/127736655/38763d6a-6176-4574-aa0a-9c3ed4a18a5b)

### What version of @mantine/* page do you have in package.json? (Note that all @mantine/* packages must have the same version in order to work correctly)

7.0.0

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

None

**Comment by rtivital** [comment] 2023-09-25 13:11
The issue is resolved in [7.0.1](https://github.com/mantinedev/mantine/releases/tag/7.0.1)

**Closed by rtivital** 2023-09-25 13:11 UTC
Labels: Completed patch
