### ISSUE TITLE
closeModal not working with openModal

### ISSUE THREAD

**Issue by Eliasmgprado** [mantinedev/mantine#2436] opened 2022-09-13 15:05 UTC
### What package has an issue

@mantine/modals

### Describe the bug

Want to open mutiple modals with openModal() function and close the modals with closeModal() function, using the modalId provided to the openModal() function. However, closeModal() is closing all opened modals, insted of the modal with the provided modalId.

### What version of @mantine/hooks page do you have in package.json?

5.3.0

### If possible, please include a link to a codesandbox with the reproduced problem

https://codesandbox.io/embed/thirsty-archimedes-bydsjh?fontsize=14&hidenavigation=1&theme=dark

### Do you know how to fix the issue

No

### Are you willing to participate in fixing this issue and create a pull request with the fix

No

**Comment by Eliasmgprado** [comment] 2022-09-14 14:11
The example uses openContextModal instead of openModal, the problem is with openModal function. As showed in the code sandbox, when multiple modal are opened with openModal function, you can`t close the modals with closeModal() function, providing the modalId, passes to the props of openModal(). The closeModal() function close all the opened modals, and not just the one of the provided id.

**Comment by UgurKacak** [comment] 2022-09-15 13:07
Hello,
The top right close button is working as expected. However, closeModal("butonId") method call inside <Button> onClick, not working as expected. Because while this call happened, ModalProvider's closeModal function faced an empty state instead of the state that holds two opened modals. I think the problem is here.

**Comment by rtivital** [comment] 2022-09-17 10:34
Fixed in 5.3.3

**Closed by rtivital** 2022-09-17 10:34 UTC
Labels: completed
